syntax = "proto3";

package pb.merchant_document;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "merchant_document/merchant_document_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/merchants_document;merchants_document";

service Merchant_documentCommandService {
    rpc Create (CreateMerchantDocumentRequest) returns (ApiResponseMerchantDocument) {}
    rpc Update (UpdateMerchantDocumentRequest) returns (ApiResponseMerchantDocument) {}
    rpc UpdateStatus(UpdateMerchantDocumentStatusRequest) returns(ApiResponseMerchantDocument){}
    rpc Trashed (TrashedMerchantDocumentRequest) returns (ApiResponseMerchantDocument) {}
    rpc Restore (RestoreMerchantDocumentRequest) returns (ApiResponseMerchantDocument) {}
    rpc DeletePermanent (DeleteMerchantDocumentPermanentRequest) returns (ApiResponseMerchantDocumentDelete) {}
    rpc RestoreAll (google.protobuf.Empty) returns (ApiResponseMerchantDocumentAll) {}
    rpc DeleteAllPermanent (google.protobuf.Empty) returns (ApiResponseMerchantDocumentAll) {}
}
