apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: point-of-sale
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ghcr.io/__GHCR_OWNER__/vertx-point-of-sale/db-migration:latest
          workingDir: /app
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
