apiVersion: v1
kind: Service
metadata:
  name: order-item
  namespace: point-of-sale
spec:
  selector:
    app: order-item
  ports:
    - name: grpc
      port: 50057
      targetPort: 50057
  type: ClusterIP
