syntax = "proto3";

package pb.role;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "role/role_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/roles;roles";

service RoleCommandService {
    rpc CreateRole(CreateRoleRequest) returns (ApiResponseRole) {}
    rpc UpdateRole(UpdateRoleRequest) returns (ApiResponseRole) {}
    rpc TrashedRole(FindByIdRoleRequest) returns (ApiResponseRole) {}
    rpc RestoreRole(FindByIdRoleRequest) returns (ApiResponseRole) {}
    rpc DeleteRolePermanent(FindByIdRoleRequest) returns (ApiResponseRoleDelete) {}
    rpc RestoreAllRole(google.protobuf.Empty) returns (ApiResponseRoleAll){}
    rpc DeleteAllRolePermanent(google.protobuf.Empty) returns (ApiResponseRoleAll){}
    rpc AssignRoleToUser(AssignRoleToUserRequest) returns (ApiResponseUserRole);
    rpc RemoveRoleFromUser(RemoveRoleFromUserRequest) returns (ApiResponseUserRole);
}
