syntax = "proto3";

package pb.role;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "role/role_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/roles;roles";

service RoleQueryService {
    rpc FindAllRole(FindAllRoleRequest) returns(ApiResponsePaginationRole){}
    rpc FindByIdRole(FindByIdRoleRequest) returns(ApiResponseRole){}
    rpc FindByActive(FindAllRoleRequest) returns(ApiResponsePaginationRoleDeleteAt){}
    rpc FindByUserId(FindByIdUserRoleRequest) returns(ApiResponsesRole){}
    rpc FindByTrashed(FindAllRoleRequest) returns(ApiResponsePaginationRoleDeleteAt){}
    rpc FindByNameRole(FindByNameRoleRequest) returns(ApiResponseRole){}

}
