apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: point-of-sale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pos-secrets
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: pos/DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: pos/DB_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: pos/POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: pos/POSTGRES_PASSWORD
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: pos/GF_SECURITY_ADMIN_PASSWORD
    - secretKey: SECRET_KEY
      remoteRef:
        key: pos/SECRET_KEY
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: pos/REDIS_PASSWORD
    - secretKey: SMTP_USER
      remoteRef:
        key: pos/SMTP_USER
    - secretKey: SMTP_PASS
      remoteRef:
        key: pos/SMTP_PASS
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: point-of-sale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pos-secrets
    kind: ClusterSecretStore
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: pos/GHCR_DOCKERCONFIGJSON
