// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: order_item.proto

package order_items

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderItemQueryService_FindAll_FullMethodName              = "/pb.OrderItemQueryService/FindAll"
	OrderItemQueryService_FindByActive_FullMethodName         = "/pb.OrderItemQueryService/FindByActive"
	OrderItemQueryService_FindByTrashed_FullMethodName        = "/pb.OrderItemQueryService/FindByTrashed"
	OrderItemQueryService_FindOrderItemByOrder_FullMethodName = "/pb.OrderItemQueryService/FindOrderItemByOrder"
)

// OrderItemQueryServiceClient is the client API for OrderItemQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderItemQueryServiceClient interface {
	FindAll(ctx context.Context, in *FindAllOrderItemRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderItem, error)
	FindByActive(ctx context.Context, in *FindAllOrderItemRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderItemDeleteAt, error)
	FindByTrashed(ctx context.Context, in *FindAllOrderItemRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderItemDeleteAt, error)
	FindOrderItemByOrder(ctx context.Context, in *FindByIdOrderItemRequest, opts ...grpc.CallOption) (*ApiResponsesOrderItem, error)
}

type orderItemQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderItemQueryServiceClient(cc grpc.ClientConnInterface) OrderItemQueryServiceClient {
	return &orderItemQueryServiceClient{cc}
}

func (c *orderItemQueryServiceClient) FindAll(ctx context.Context, in *FindAllOrderItemRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationOrderItem)
	err := c.cc.Invoke(ctx, OrderItemQueryService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderItemQueryServiceClient) FindByActive(ctx context.Context, in *FindAllOrderItemRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderItemDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationOrderItemDeleteAt)
	err := c.cc.Invoke(ctx, OrderItemQueryService_FindByActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderItemQueryServiceClient) FindByTrashed(ctx context.Context, in *FindAllOrderItemRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderItemDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationOrderItemDeleteAt)
	err := c.cc.Invoke(ctx, OrderItemQueryService_FindByTrashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderItemQueryServiceClient) FindOrderItemByOrder(ctx context.Context, in *FindByIdOrderItemRequest, opts ...grpc.CallOption) (*ApiResponsesOrderItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsesOrderItem)
	err := c.cc.Invoke(ctx, OrderItemQueryService_FindOrderItemByOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderItemQueryServiceServer is the server API for OrderItemQueryService service.
// All implementations must embed UnimplementedOrderItemQueryServiceServer
// for forward compatibility.
type OrderItemQueryServiceServer interface {
	FindAll(context.Context, *FindAllOrderItemRequest) (*ApiResponsePaginationOrderItem, error)
	FindByActive(context.Context, *FindAllOrderItemRequest) (*ApiResponsePaginationOrderItemDeleteAt, error)
	FindByTrashed(context.Context, *FindAllOrderItemRequest) (*ApiResponsePaginationOrderItemDeleteAt, error)
	FindOrderItemByOrder(context.Context, *FindByIdOrderItemRequest) (*ApiResponsesOrderItem, error)
	mustEmbedUnimplementedOrderItemQueryServiceServer()
}

// UnimplementedOrderItemQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderItemQueryServiceServer struct{}

func (UnimplementedOrderItemQueryServiceServer) FindAll(context.Context, *FindAllOrderItemRequest) (*ApiResponsePaginationOrderItem, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedOrderItemQueryServiceServer) FindByActive(context.Context, *FindAllOrderItemRequest) (*ApiResponsePaginationOrderItemDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByActive not implemented")
}
func (UnimplementedOrderItemQueryServiceServer) FindByTrashed(context.Context, *FindAllOrderItemRequest) (*ApiResponsePaginationOrderItemDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByTrashed not implemented")
}
func (UnimplementedOrderItemQueryServiceServer) FindOrderItemByOrder(context.Context, *FindByIdOrderItemRequest) (*ApiResponsesOrderItem, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOrderItemByOrder not implemented")
}
func (UnimplementedOrderItemQueryServiceServer) mustEmbedUnimplementedOrderItemQueryServiceServer() {}
func (UnimplementedOrderItemQueryServiceServer) testEmbeddedByValue()                               {}

// UnsafeOrderItemQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderItemQueryServiceServer will
// result in compilation errors.
type UnsafeOrderItemQueryServiceServer interface {
	mustEmbedUnimplementedOrderItemQueryServiceServer()
}

func RegisterOrderItemQueryServiceServer(s grpc.ServiceRegistrar, srv OrderItemQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderItemQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderItemQueryService_ServiceDesc, srv)
}

func _OrderItemQueryService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderItemQueryServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderItemQueryService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderItemQueryServiceServer).FindAll(ctx, req.(*FindAllOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderItemQueryService_FindByActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderItemQueryServiceServer).FindByActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderItemQueryService_FindByActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderItemQueryServiceServer).FindByActive(ctx, req.(*FindAllOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderItemQueryService_FindByTrashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderItemQueryServiceServer).FindByTrashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderItemQueryService_FindByTrashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderItemQueryServiceServer).FindByTrashed(ctx, req.(*FindAllOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderItemQueryService_FindOrderItemByOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderItemQueryServiceServer).FindOrderItemByOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderItemQueryService_FindOrderItemByOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderItemQueryServiceServer).FindOrderItemByOrder(ctx, req.(*FindByIdOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderItemQueryService_ServiceDesc is the grpc.ServiceDesc for OrderItemQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderItemQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderItemQueryService",
	HandlerType: (*OrderItemQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _OrderItemQueryService_FindAll_Handler,
		},
		{
			MethodName: "FindByActive",
			Handler:    _OrderItemQueryService_FindByActive_Handler,
		},
		{
			MethodName: "FindByTrashed",
			Handler:    _OrderItemQueryService_FindByTrashed_Handler,
		},
		{
			MethodName: "FindOrderItemByOrder",
			Handler:    _OrderItemQueryService_FindOrderItemByOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_item.proto",
}

const (
	OrderItemCommandService_CreateOrderItem_FullMethodName = "/pb.OrderItemCommandService/CreateOrderItem"
	OrderItemCommandService_UpdateOrderItem_FullMethodName = "/pb.OrderItemCommandService/UpdateOrderItem"
	OrderItemCommandService_DeleteOrderItem_FullMethodName = "/pb.OrderItemCommandService/DeleteOrderItem"
)

// OrderItemCommandServiceClient is the client API for OrderItemCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderItemCommandServiceClient interface {
	CreateOrderItem(ctx context.Context, in *CreateOrderItemRecordRequest, opts ...grpc.CallOption) (*ApiResponseOrderItem, error)
	UpdateOrderItem(ctx context.Context, in *UpdateOrderItemRecordRequest, opts ...grpc.CallOption) (*ApiResponseOrderItem, error)
	DeleteOrderItem(ctx context.Context, in *DeleteOrderItemRecordRequest, opts ...grpc.CallOption) (*ApiResponseOrderItemDelete, error)
}

type orderItemCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderItemCommandServiceClient(cc grpc.ClientConnInterface) OrderItemCommandServiceClient {
	return &orderItemCommandServiceClient{cc}
}

func (c *orderItemCommandServiceClient) CreateOrderItem(ctx context.Context, in *CreateOrderItemRecordRequest, opts ...grpc.CallOption) (*ApiResponseOrderItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderItem)
	err := c.cc.Invoke(ctx, OrderItemCommandService_CreateOrderItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderItemCommandServiceClient) UpdateOrderItem(ctx context.Context, in *UpdateOrderItemRecordRequest, opts ...grpc.CallOption) (*ApiResponseOrderItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderItem)
	err := c.cc.Invoke(ctx, OrderItemCommandService_UpdateOrderItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderItemCommandServiceClient) DeleteOrderItem(ctx context.Context, in *DeleteOrderItemRecordRequest, opts ...grpc.CallOption) (*ApiResponseOrderItemDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderItemDelete)
	err := c.cc.Invoke(ctx, OrderItemCommandService_DeleteOrderItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderItemCommandServiceServer is the server API for OrderItemCommandService service.
// All implementations must embed UnimplementedOrderItemCommandServiceServer
// for forward compatibility.
type OrderItemCommandServiceServer interface {
	CreateOrderItem(context.Context, *CreateOrderItemRecordRequest) (*ApiResponseOrderItem, error)
	UpdateOrderItem(context.Context, *UpdateOrderItemRecordRequest) (*ApiResponseOrderItem, error)
	DeleteOrderItem(context.Context, *DeleteOrderItemRecordRequest) (*ApiResponseOrderItemDelete, error)
	mustEmbedUnimplementedOrderItemCommandServiceServer()
}

// UnimplementedOrderItemCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderItemCommandServiceServer struct{}

func (UnimplementedOrderItemCommandServiceServer) CreateOrderItem(context.Context, *CreateOrderItemRecordRequest) (*ApiResponseOrderItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrderItem not implemented")
}
func (UnimplementedOrderItemCommandServiceServer) UpdateOrderItem(context.Context, *UpdateOrderItemRecordRequest) (*ApiResponseOrderItem, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrderItem not implemented")
}
func (UnimplementedOrderItemCommandServiceServer) DeleteOrderItem(context.Context, *DeleteOrderItemRecordRequest) (*ApiResponseOrderItemDelete, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOrderItem not implemented")
}
func (UnimplementedOrderItemCommandServiceServer) mustEmbedUnimplementedOrderItemCommandServiceServer() {
}
func (UnimplementedOrderItemCommandServiceServer) testEmbeddedByValue() {}

// UnsafeOrderItemCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderItemCommandServiceServer will
// result in compilation errors.
type UnsafeOrderItemCommandServiceServer interface {
	mustEmbedUnimplementedOrderItemCommandServiceServer()
}

func RegisterOrderItemCommandServiceServer(s grpc.ServiceRegistrar, srv OrderItemCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderItemCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderItemCommandService_ServiceDesc, srv)
}

func _OrderItemCommandService_CreateOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderItemRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderItemCommandServiceServer).CreateOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderItemCommandService_CreateOrderItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderItemCommandServiceServer).CreateOrderItem(ctx, req.(*CreateOrderItemRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderItemCommandService_UpdateOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderItemRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderItemCommandServiceServer).UpdateOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderItemCommandService_UpdateOrderItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderItemCommandServiceServer).UpdateOrderItem(ctx, req.(*UpdateOrderItemRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderItemCommandService_DeleteOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderItemRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderItemCommandServiceServer).DeleteOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderItemCommandService_DeleteOrderItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderItemCommandServiceServer).DeleteOrderItem(ctx, req.(*DeleteOrderItemRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderItemCommandService_ServiceDesc is the grpc.ServiceDesc for OrderItemCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderItemCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderItemCommandService",
	HandlerType: (*OrderItemCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrderItem",
			Handler:    _OrderItemCommandService_CreateOrderItem_Handler,
		},
		{
			MethodName: "UpdateOrderItem",
			Handler:    _OrderItemCommandService_UpdateOrderItem_Handler,
		},
		{
			MethodName: "DeleteOrderItem",
			Handler:    _OrderItemCommandService_DeleteOrderItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_item.proto",
}
