syntax = "proto3";

package pb.category;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "category/category_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/categories;categories";

service CategoryQueryService {
    rpc FindByActive(FindAllCategoryRequest) returns (ApiResponsePaginationCategoryDeleteAt) {}
    rpc FindAll(FindAllCategoryRequest) returns (ApiResponsePaginationCategory);
    rpc FindById(FindByIdCategoryRequest) returns (ApiResponseCategory);
    rpc FindByTrashed(FindAllCategoryRequest) returns (ApiResponsePaginationCategoryDeleteAt) {}
    rpc FindByName(FindByNameCategoryRequest) returns (ApiResponseCategory);
    rpc FindByIds(FindByIdsCategoryRequest) returns (ApiResponsesCategory);

}
