syntax = "proto3";

package pb.category;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "category/category_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/categories;categories";

service CategoryCommandService {
    rpc Create(CreateCategoryRequest) returns (ApiResponseCategory);
    rpc Update(UpdateCategoryRequest) returns (ApiResponseCategory);
    rpc TrashedCategory(FindByIdCategoryRequest) returns (ApiResponseCategoryDeleteAt);
    rpc RestoreCategory(FindByIdCategoryRequest) returns (ApiResponseCategoryDeleteAt);
    rpc DeleteCategoryPermanent(FindByIdCategoryRequest) returns (ApiResponseCategoryDelete);
    rpc RestoreAllCategory(google.protobuf.Empty) returns (ApiResponseCategoryAll){}
    rpc DeleteAllCategoryPermanent(google.protobuf.Empty) returns (ApiResponseCategoryAll){}
}
