apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- redis-cluster-configmap.yaml
- redis-cluster-init-job.yaml
- redis-cluster-service.yaml
- redis-cluster-statefulset.yaml
- redis-pvc.yaml
- redis-service.yaml
