// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: merchant_document/merchant_document_command.proto

package merchants_document

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_merchant_document_merchant_document_command_proto protoreflect.FileDescriptor

const file_merchant_document_merchant_document_command_proto_rawDesc = "" +
	"\n" +
	"1merchant_document/merchant_document_command.proto\x12\x14pb.merchant_document\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a0merchant_document/merchant_document_common.proto2\xc6\a\n" +
	"\x1fMerchant_documentCommandService\x12r\n" +
	"\x06Create\x123.pb.merchant_document.CreateMerchantDocumentRequest\x1a1.pb.merchant_document.ApiResponseMerchantDocument\"\x00\x12r\n" +
	"\x06Update\x123.pb.merchant_document.UpdateMerchantDocumentRequest\x1a1.pb.merchant_document.ApiResponseMerchantDocument\"\x00\x12~\n" +
	"\fUpdateStatus\x129.pb.merchant_document.UpdateMerchantDocumentStatusRequest\x1a1.pb.merchant_document.ApiResponseMerchantDocument\"\x00\x12t\n" +
	"\aTrashed\x124.pb.merchant_document.TrashedMerchantDocumentRequest\x1a1.pb.merchant_document.ApiResponseMerchantDocument\"\x00\x12t\n" +
	"\aRestore\x124.pb.merchant_document.RestoreMerchantDocumentRequest\x1a1.pb.merchant_document.ApiResponseMerchantDocument\"\x00\x12\x8a\x01\n" +
	"\x0fDeletePermanent\x12<.pb.merchant_document.DeleteMerchantDocumentPermanentRequest\x1a7.pb.merchant_document.ApiResponseMerchantDocumentDelete\"\x00\x12\\\n" +
	"\n" +
	"RestoreAll\x12\x16.google.protobuf.Empty\x1a4.pb.merchant_document.ApiResponseMerchantDocumentAll\"\x00\x12d\n" +
	"\x12DeleteAllPermanent\x12\x16.google.protobuf.Empty\x1a4.pb.merchant_document.ApiResponseMerchantDocumentAll\"\x00BWZUgithub.com/MamangRust/monolith-point-of-sale-pb/merchants_document;merchants_documentb\x06proto3"

var file_merchant_document_merchant_document_command_proto_goTypes = []any{
	(*CreateMerchantDocumentRequest)(nil),          // 0: pb.merchant_document.CreateMerchantDocumentRequest
	(*UpdateMerchantDocumentRequest)(nil),          // 1: pb.merchant_document.UpdateMerchantDocumentRequest
	(*UpdateMerchantDocumentStatusRequest)(nil),    // 2: pb.merchant_document.UpdateMerchantDocumentStatusRequest
	(*TrashedMerchantDocumentRequest)(nil),         // 3: pb.merchant_document.TrashedMerchantDocumentRequest
	(*RestoreMerchantDocumentRequest)(nil),         // 4: pb.merchant_document.RestoreMerchantDocumentRequest
	(*DeleteMerchantDocumentPermanentRequest)(nil), // 5: pb.merchant_document.DeleteMerchantDocumentPermanentRequest
	(*emptypb.Empty)(nil),                          // 6: google.protobuf.Empty
	(*ApiResponseMerchantDocument)(nil),            // 7: pb.merchant_document.ApiResponseMerchantDocument
	(*ApiResponseMerchantDocumentDelete)(nil),      // 8: pb.merchant_document.ApiResponseMerchantDocumentDelete
	(*ApiResponseMerchantDocumentAll)(nil),         // 9: pb.merchant_document.ApiResponseMerchantDocumentAll
}
var file_merchant_document_merchant_document_command_proto_depIdxs = []int32{
	0, // 0: pb.merchant_document.Merchant_documentCommandService.Create:input_type -> pb.merchant_document.CreateMerchantDocumentRequest
	1, // 1: pb.merchant_document.Merchant_documentCommandService.Update:input_type -> pb.merchant_document.UpdateMerchantDocumentRequest
	2, // 2: pb.merchant_document.Merchant_documentCommandService.UpdateStatus:input_type -> pb.merchant_document.UpdateMerchantDocumentStatusRequest
	3, // 3: pb.merchant_document.Merchant_documentCommandService.Trashed:input_type -> pb.merchant_document.TrashedMerchantDocumentRequest
	4, // 4: pb.merchant_document.Merchant_documentCommandService.Restore:input_type -> pb.merchant_document.RestoreMerchantDocumentRequest
	5, // 5: pb.merchant_document.Merchant_documentCommandService.DeletePermanent:input_type -> pb.merchant_document.DeleteMerchantDocumentPermanentRequest
	6, // 6: pb.merchant_document.Merchant_documentCommandService.RestoreAll:input_type -> google.protobuf.Empty
	6, // 7: pb.merchant_document.Merchant_documentCommandService.DeleteAllPermanent:input_type -> google.protobuf.Empty
	7, // 8: pb.merchant_document.Merchant_documentCommandService.Create:output_type -> pb.merchant_document.ApiResponseMerchantDocument
	7, // 9: pb.merchant_document.Merchant_documentCommandService.Update:output_type -> pb.merchant_document.ApiResponseMerchantDocument
	7, // 10: pb.merchant_document.Merchant_documentCommandService.UpdateStatus:output_type -> pb.merchant_document.ApiResponseMerchantDocument
	7, // 11: pb.merchant_document.Merchant_documentCommandService.Trashed:output_type -> pb.merchant_document.ApiResponseMerchantDocument
	7, // 12: pb.merchant_document.Merchant_documentCommandService.Restore:output_type -> pb.merchant_document.ApiResponseMerchantDocument
	8, // 13: pb.merchant_document.Merchant_documentCommandService.DeletePermanent:output_type -> pb.merchant_document.ApiResponseMerchantDocumentDelete
	9, // 14: pb.merchant_document.Merchant_documentCommandService.RestoreAll:output_type -> pb.merchant_document.ApiResponseMerchantDocumentAll
	9, // 15: pb.merchant_document.Merchant_documentCommandService.DeleteAllPermanent:output_type -> pb.merchant_document.ApiResponseMerchantDocumentAll
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_merchant_document_merchant_document_command_proto_init() }
func file_merchant_document_merchant_document_command_proto_init() {
	if File_merchant_document_merchant_document_command_proto != nil {
		return
	}
	file_merchant_document_merchant_document_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_document_merchant_document_command_proto_rawDesc), len(file_merchant_document_merchant_document_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_document_merchant_document_command_proto_goTypes,
		DependencyIndexes: file_merchant_document_merchant_document_command_proto_depIdxs,
	}.Build()
	File_merchant_document_merchant_document_command_proto = out.File
	file_merchant_document_merchant_document_command_proto_goTypes = nil
	file_merchant_document_merchant_document_command_proto_depIdxs = nil
}
