// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: merchant_document/merchant_document_query.proto

package merchants_document

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_merchant_document_merchant_document_query_proto protoreflect.FileDescriptor

const file_merchant_document_merchant_document_query_proto_rawDesc = "" +
	"\n" +
	"/merchant_document/merchant_document_query.proto\x12\x14pb.merchant_document\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a0merchant_document/merchant_document_common.proto2\xab\x04\n" +
	"\x1dMerchant_documentQueryService\x12\x7f\n" +
	"\aFindAll\x125.pb.merchant_document.FindAllMerchantDocumentsRequest\x1a;.pb.merchant_document.ApiResponsePaginationMerchantDocument\"\x00\x12\x85\x01\n" +
	"\rFindAllActive\x125.pb.merchant_document.FindAllMerchantDocumentsRequest\x1a;.pb.merchant_document.ApiResponsePaginationMerchantDocument\"\x00\x12v\n" +
	"\bFindById\x125.pb.merchant_document.FindMerchantDocumentByIdRequest\x1a1.pb.merchant_document.ApiResponseMerchantDocument\"\x00\x12\x88\x01\n" +
	"\x0eFindAllTrashed\x125.pb.merchant_document.FindAllMerchantDocumentsRequest\x1a=.pb.merchant_document.ApiResponsePaginationMerchantDocumentAt\"\x00BWZUgithub.com/MamangRust/monolith-point-of-sale-pb/merchants_document;merchants_documentb\x06proto3"

var file_merchant_document_merchant_document_query_proto_goTypes = []any{
	(*FindAllMerchantDocumentsRequest)(nil),         // 0: pb.merchant_document.FindAllMerchantDocumentsRequest
	(*FindMerchantDocumentByIdRequest)(nil),         // 1: pb.merchant_document.FindMerchantDocumentByIdRequest
	(*ApiResponsePaginationMerchantDocument)(nil),   // 2: pb.merchant_document.ApiResponsePaginationMerchantDocument
	(*ApiResponseMerchantDocument)(nil),             // 3: pb.merchant_document.ApiResponseMerchantDocument
	(*ApiResponsePaginationMerchantDocumentAt)(nil), // 4: pb.merchant_document.ApiResponsePaginationMerchantDocumentAt
}
var file_merchant_document_merchant_document_query_proto_depIdxs = []int32{
	0, // 0: pb.merchant_document.Merchant_documentQueryService.FindAll:input_type -> pb.merchant_document.FindAllMerchantDocumentsRequest
	0, // 1: pb.merchant_document.Merchant_documentQueryService.FindAllActive:input_type -> pb.merchant_document.FindAllMerchantDocumentsRequest
	1, // 2: pb.merchant_document.Merchant_documentQueryService.FindById:input_type -> pb.merchant_document.FindMerchantDocumentByIdRequest
	0, // 3: pb.merchant_document.Merchant_documentQueryService.FindAllTrashed:input_type -> pb.merchant_document.FindAllMerchantDocumentsRequest
	2, // 4: pb.merchant_document.Merchant_documentQueryService.FindAll:output_type -> pb.merchant_document.ApiResponsePaginationMerchantDocument
	2, // 5: pb.merchant_document.Merchant_documentQueryService.FindAllActive:output_type -> pb.merchant_document.ApiResponsePaginationMerchantDocument
	3, // 6: pb.merchant_document.Merchant_documentQueryService.FindById:output_type -> pb.merchant_document.ApiResponseMerchantDocument
	4, // 7: pb.merchant_document.Merchant_documentQueryService.FindAllTrashed:output_type -> pb.merchant_document.ApiResponsePaginationMerchantDocumentAt
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_merchant_document_merchant_document_query_proto_init() }
func file_merchant_document_merchant_document_query_proto_init() {
	if File_merchant_document_merchant_document_query_proto != nil {
		return
	}
	file_merchant_document_merchant_document_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_document_merchant_document_query_proto_rawDesc), len(file_merchant_document_merchant_document_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_document_merchant_document_query_proto_goTypes,
		DependencyIndexes: file_merchant_document_merchant_document_query_proto_depIdxs,
	}.Build()
	File_merchant_document_merchant_document_query_proto = out.File
	file_merchant_document_merchant_document_query_proto_goTypes = nil
	file_merchant_document_merchant_document_query_proto_depIdxs = nil
}
