// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: role/role_query.proto

package roles

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoleQueryService_FindAllRole_FullMethodName    = "/pb.role.RoleQueryService/FindAllRole"
	RoleQueryService_FindByIdRole_FullMethodName   = "/pb.role.RoleQueryService/FindByIdRole"
	RoleQueryService_FindByActive_FullMethodName   = "/pb.role.RoleQueryService/FindByActive"
	RoleQueryService_FindByUserId_FullMethodName   = "/pb.role.RoleQueryService/FindByUserId"
	RoleQueryService_FindByTrashed_FullMethodName  = "/pb.role.RoleQueryService/FindByTrashed"
	RoleQueryService_FindByNameRole_FullMethodName = "/pb.role.RoleQueryService/FindByNameRole"
)

// RoleQueryServiceClient is the client API for RoleQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoleQueryServiceClient interface {
	FindAllRole(ctx context.Context, in *FindAllRoleRequest, opts ...grpc.CallOption) (*ApiResponsePaginationRole, error)
	FindByIdRole(ctx context.Context, in *FindByIdRoleRequest, opts ...grpc.CallOption) (*ApiResponseRole, error)
	FindByActive(ctx context.Context, in *FindAllRoleRequest, opts ...grpc.CallOption) (*ApiResponsePaginationRoleDeleteAt, error)
	FindByUserId(ctx context.Context, in *FindByIdUserRoleRequest, opts ...grpc.CallOption) (*ApiResponsesRole, error)
	FindByTrashed(ctx context.Context, in *FindAllRoleRequest, opts ...grpc.CallOption) (*ApiResponsePaginationRoleDeleteAt, error)
	FindByNameRole(ctx context.Context, in *FindByNameRoleRequest, opts ...grpc.CallOption) (*ApiResponseRole, error)
}

type roleQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleQueryServiceClient(cc grpc.ClientConnInterface) RoleQueryServiceClient {
	return &roleQueryServiceClient{cc}
}

func (c *roleQueryServiceClient) FindAllRole(ctx context.Context, in *FindAllRoleRequest, opts ...grpc.CallOption) (*ApiResponsePaginationRole, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationRole)
	err := c.cc.Invoke(ctx, RoleQueryService_FindAllRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleQueryServiceClient) FindByIdRole(ctx context.Context, in *FindByIdRoleRequest, opts ...grpc.CallOption) (*ApiResponseRole, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseRole)
	err := c.cc.Invoke(ctx, RoleQueryService_FindByIdRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleQueryServiceClient) FindByActive(ctx context.Context, in *FindAllRoleRequest, opts ...grpc.CallOption) (*ApiResponsePaginationRoleDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationRoleDeleteAt)
	err := c.cc.Invoke(ctx, RoleQueryService_FindByActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleQueryServiceClient) FindByUserId(ctx context.Context, in *FindByIdUserRoleRequest, opts ...grpc.CallOption) (*ApiResponsesRole, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsesRole)
	err := c.cc.Invoke(ctx, RoleQueryService_FindByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleQueryServiceClient) FindByTrashed(ctx context.Context, in *FindAllRoleRequest, opts ...grpc.CallOption) (*ApiResponsePaginationRoleDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationRoleDeleteAt)
	err := c.cc.Invoke(ctx, RoleQueryService_FindByTrashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleQueryServiceClient) FindByNameRole(ctx context.Context, in *FindByNameRoleRequest, opts ...grpc.CallOption) (*ApiResponseRole, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseRole)
	err := c.cc.Invoke(ctx, RoleQueryService_FindByNameRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleQueryServiceServer is the server API for RoleQueryService service.
// All implementations must embed UnimplementedRoleQueryServiceServer
// for forward compatibility.
type RoleQueryServiceServer interface {
	FindAllRole(context.Context, *FindAllRoleRequest) (*ApiResponsePaginationRole, error)
	FindByIdRole(context.Context, *FindByIdRoleRequest) (*ApiResponseRole, error)
	FindByActive(context.Context, *FindAllRoleRequest) (*ApiResponsePaginationRoleDeleteAt, error)
	FindByUserId(context.Context, *FindByIdUserRoleRequest) (*ApiResponsesRole, error)
	FindByTrashed(context.Context, *FindAllRoleRequest) (*ApiResponsePaginationRoleDeleteAt, error)
	FindByNameRole(context.Context, *FindByNameRoleRequest) (*ApiResponseRole, error)
	mustEmbedUnimplementedRoleQueryServiceServer()
}

// UnimplementedRoleQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoleQueryServiceServer struct{}

func (UnimplementedRoleQueryServiceServer) FindAllRole(context.Context, *FindAllRoleRequest) (*ApiResponsePaginationRole, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAllRole not implemented")
}
func (UnimplementedRoleQueryServiceServer) FindByIdRole(context.Context, *FindByIdRoleRequest) (*ApiResponseRole, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByIdRole not implemented")
}
func (UnimplementedRoleQueryServiceServer) FindByActive(context.Context, *FindAllRoleRequest) (*ApiResponsePaginationRoleDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByActive not implemented")
}
func (UnimplementedRoleQueryServiceServer) FindByUserId(context.Context, *FindByIdUserRoleRequest) (*ApiResponsesRole, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByUserId not implemented")
}
func (UnimplementedRoleQueryServiceServer) FindByTrashed(context.Context, *FindAllRoleRequest) (*ApiResponsePaginationRoleDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByTrashed not implemented")
}
func (UnimplementedRoleQueryServiceServer) FindByNameRole(context.Context, *FindByNameRoleRequest) (*ApiResponseRole, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByNameRole not implemented")
}
func (UnimplementedRoleQueryServiceServer) mustEmbedUnimplementedRoleQueryServiceServer() {}
func (UnimplementedRoleQueryServiceServer) testEmbeddedByValue()                          {}

// UnsafeRoleQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleQueryServiceServer will
// result in compilation errors.
type UnsafeRoleQueryServiceServer interface {
	mustEmbedUnimplementedRoleQueryServiceServer()
}

func RegisterRoleQueryServiceServer(s grpc.ServiceRegistrar, srv RoleQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedRoleQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoleQueryService_ServiceDesc, srv)
}

func _RoleQueryService_FindAllRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleQueryServiceServer).FindAllRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleQueryService_FindAllRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleQueryServiceServer).FindAllRole(ctx, req.(*FindAllRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleQueryService_FindByIdRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleQueryServiceServer).FindByIdRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleQueryService_FindByIdRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleQueryServiceServer).FindByIdRole(ctx, req.(*FindByIdRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleQueryService_FindByActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleQueryServiceServer).FindByActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleQueryService_FindByActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleQueryServiceServer).FindByActive(ctx, req.(*FindAllRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleQueryService_FindByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleQueryServiceServer).FindByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleQueryService_FindByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleQueryServiceServer).FindByUserId(ctx, req.(*FindByIdUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleQueryService_FindByTrashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleQueryServiceServer).FindByTrashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleQueryService_FindByTrashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleQueryServiceServer).FindByTrashed(ctx, req.(*FindAllRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleQueryService_FindByNameRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByNameRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleQueryServiceServer).FindByNameRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleQueryService_FindByNameRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleQueryServiceServer).FindByNameRole(ctx, req.(*FindByNameRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleQueryService_ServiceDesc is the grpc.ServiceDesc for RoleQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.role.RoleQueryService",
	HandlerType: (*RoleQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAllRole",
			Handler:    _RoleQueryService_FindAllRole_Handler,
		},
		{
			MethodName: "FindByIdRole",
			Handler:    _RoleQueryService_FindByIdRole_Handler,
		},
		{
			MethodName: "FindByActive",
			Handler:    _RoleQueryService_FindByActive_Handler,
		},
		{
			MethodName: "FindByUserId",
			Handler:    _RoleQueryService_FindByUserId_Handler,
		},
		{
			MethodName: "FindByTrashed",
			Handler:    _RoleQueryService_FindByTrashed_Handler,
		},
		{
			MethodName: "FindByNameRole",
			Handler:    _RoleQueryService_FindByNameRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "role/role_query.proto",
}
