// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: role/role_command.proto

package roles

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_role_role_command_proto protoreflect.FileDescriptor

const file_role_role_command_proto_rawDesc = "" +
	"\n" +
	"\x17role/role_command.proto\x12\apb.role\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16role/role_common.proto2\xcf\x05\n" +
	"\x12RoleCommandService\x12D\n" +
	"\n" +
	"CreateRole\x12\x1a.pb.role.CreateRoleRequest\x1a\x18.pb.role.ApiResponseRole\"\x00\x12D\n" +
	"\n" +
	"UpdateRole\x12\x1a.pb.role.UpdateRoleRequest\x1a\x18.pb.role.ApiResponseRole\"\x00\x12G\n" +
	"\vTrashedRole\x12\x1c.pb.role.FindByIdRoleRequest\x1a\x18.pb.role.ApiResponseRole\"\x00\x12G\n" +
	"\vRestoreRole\x12\x1c.pb.role.FindByIdRoleRequest\x1a\x18.pb.role.ApiResponseRole\"\x00\x12U\n" +
	"\x13DeleteRolePermanent\x12\x1c.pb.role.FindByIdRoleRequest\x1a\x1e.pb.role.ApiResponseRoleDelete\"\x00\x12G\n" +
	"\x0eRestoreAllRole\x12\x16.google.protobuf.Empty\x1a\x1b.pb.role.ApiResponseRoleAll\"\x00\x12O\n" +
	"\x16DeleteAllRolePermanent\x12\x16.google.protobuf.Empty\x1a\x1b.pb.role.ApiResponseRoleAll\"\x00\x12R\n" +
	"\x10AssignRoleToUser\x12 .pb.role.AssignRoleToUserRequest\x1a\x1c.pb.role.ApiResponseUserRole\x12V\n" +
	"\x12RemoveRoleFromUser\x12\".pb.role.RemoveRoleFromUserRequest\x1a\x1c.pb.role.ApiResponseUserRoleB=Z;github.com/MamangRust/monolith-point-of-sale-pb/roles;rolesb\x06proto3"

var file_role_role_command_proto_goTypes = []any{
	(*CreateRoleRequest)(nil),         // 0: pb.role.CreateRoleRequest
	(*UpdateRoleRequest)(nil),         // 1: pb.role.UpdateRoleRequest
	(*FindByIdRoleRequest)(nil),       // 2: pb.role.FindByIdRoleRequest
	(*emptypb.Empty)(nil),             // 3: google.protobuf.Empty
	(*AssignRoleToUserRequest)(nil),   // 4: pb.role.AssignRoleToUserRequest
	(*RemoveRoleFromUserRequest)(nil), // 5: pb.role.RemoveRoleFromUserRequest
	(*ApiResponseRole)(nil),           // 6: pb.role.ApiResponseRole
	(*ApiResponseRoleDelete)(nil),     // 7: pb.role.ApiResponseRoleDelete
	(*ApiResponseRoleAll)(nil),        // 8: pb.role.ApiResponseRoleAll
	(*ApiResponseUserRole)(nil),       // 9: pb.role.ApiResponseUserRole
}
var file_role_role_command_proto_depIdxs = []int32{
	0, // 0: pb.role.RoleCommandService.CreateRole:input_type -> pb.role.CreateRoleRequest
	1, // 1: pb.role.RoleCommandService.UpdateRole:input_type -> pb.role.UpdateRoleRequest
	2, // 2: pb.role.RoleCommandService.TrashedRole:input_type -> pb.role.FindByIdRoleRequest
	2, // 3: pb.role.RoleCommandService.RestoreRole:input_type -> pb.role.FindByIdRoleRequest
	2, // 4: pb.role.RoleCommandService.DeleteRolePermanent:input_type -> pb.role.FindByIdRoleRequest
	3, // 5: pb.role.RoleCommandService.RestoreAllRole:input_type -> google.protobuf.Empty
	3, // 6: pb.role.RoleCommandService.DeleteAllRolePermanent:input_type -> google.protobuf.Empty
	4, // 7: pb.role.RoleCommandService.AssignRoleToUser:input_type -> pb.role.AssignRoleToUserRequest
	5, // 8: pb.role.RoleCommandService.RemoveRoleFromUser:input_type -> pb.role.RemoveRoleFromUserRequest
	6, // 9: pb.role.RoleCommandService.CreateRole:output_type -> pb.role.ApiResponseRole
	6, // 10: pb.role.RoleCommandService.UpdateRole:output_type -> pb.role.ApiResponseRole
	6, // 11: pb.role.RoleCommandService.TrashedRole:output_type -> pb.role.ApiResponseRole
	6, // 12: pb.role.RoleCommandService.RestoreRole:output_type -> pb.role.ApiResponseRole
	7, // 13: pb.role.RoleCommandService.DeleteRolePermanent:output_type -> pb.role.ApiResponseRoleDelete
	8, // 14: pb.role.RoleCommandService.RestoreAllRole:output_type -> pb.role.ApiResponseRoleAll
	8, // 15: pb.role.RoleCommandService.DeleteAllRolePermanent:output_type -> pb.role.ApiResponseRoleAll
	9, // 16: pb.role.RoleCommandService.AssignRoleToUser:output_type -> pb.role.ApiResponseUserRole
	9, // 17: pb.role.RoleCommandService.RemoveRoleFromUser:output_type -> pb.role.ApiResponseUserRole
	9, // [9:18] is the sub-list for method output_type
	0, // [0:9] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_role_role_command_proto_init() }
func file_role_role_command_proto_init() {
	if File_role_role_command_proto != nil {
		return
	}
	file_role_role_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_role_command_proto_rawDesc), len(file_role_role_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_role_command_proto_goTypes,
		DependencyIndexes: file_role_role_command_proto_depIdxs,
	}.Build()
	File_role_role_command_proto = out.File
	file_role_role_command_proto_goTypes = nil
	file_role_role_command_proto_depIdxs = nil
}
