// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: role/role_common.proto

package roles

import (
	common "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRoleRequest) Reset() {
	*x = FindAllRoleRequest{}
	mi := &file_role_role_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRoleRequest) ProtoMessage() {}

func (x *FindAllRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRoleRequest.ProtoReflect.Descriptor instead.
func (*FindAllRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllRoleRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllRoleRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllRoleRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int32                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdRoleRequest) Reset() {
	*x = FindByIdRoleRequest{}
	mi := &file_role_role_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdRoleRequest) ProtoMessage() {}

func (x *FindByIdRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdRoleRequest.ProtoReflect.Descriptor instead.
func (*FindByIdRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{1}
}

func (x *FindByIdRoleRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type FindByIdUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdUserRoleRequest) Reset() {
	*x = FindByIdUserRoleRequest{}
	mi := &file_role_role_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdUserRoleRequest) ProtoMessage() {}

func (x *FindByIdUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdUserRoleRequest.ProtoReflect.Descriptor instead.
func (*FindByIdUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{2}
}

func (x *FindByIdUserRoleRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FindByNameRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByNameRoleRequest) Reset() {
	*x = FindByNameRoleRequest{}
	mi := &file_role_role_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByNameRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByNameRoleRequest) ProtoMessage() {}

func (x *FindByNameRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByNameRoleRequest.ProtoReflect.Descriptor instead.
func (*FindByNameRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{3}
}

func (x *FindByNameRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AssignRoleToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleToUserRequest) Reset() {
	*x = AssignRoleToUserRequest{}
	mi := &file_role_role_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleToUserRequest) ProtoMessage() {}

func (x *AssignRoleToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleToUserRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleToUserRequest) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{4}
}

func (x *AssignRoleToUserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignRoleToUserRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RemoveRoleFromUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoleFromUserRequest) Reset() {
	*x = RemoveRoleFromUserRequest{}
	mi := &file_role_role_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoleFromUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoleFromUserRequest) ProtoMessage() {}

func (x *RemoveRoleFromUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoleFromUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoleFromUserRequest) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveRoleFromUserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveRoleFromUserRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_role_role_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_role_role_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRoleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponse) Reset() {
	*x = RoleResponse{}
	mi := &file_role_role_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponse) ProtoMessage() {}

func (x *RoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponse.ProtoReflect.Descriptor instead.
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{8}
}

func (x *RoleResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RoleResponseDeleteAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponseDeleteAt) Reset() {
	*x = RoleResponseDeleteAt{}
	mi := &file_role_role_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponseDeleteAt) ProtoMessage() {}

func (x *RoleResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*RoleResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{9}
}

func (x *RoleResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RoleResponseDeleteAt) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type ApiResponseRoleAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseRoleAll) Reset() {
	*x = ApiResponseRoleAll{}
	mi := &file_role_role_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseRoleAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseRoleAll) ProtoMessage() {}

func (x *ApiResponseRoleAll) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseRoleAll.ProtoReflect.Descriptor instead.
func (*ApiResponseRoleAll) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponseRoleAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseRoleAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseRoleDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseRoleDelete) Reset() {
	*x = ApiResponseRoleDelete{}
	mi := &file_role_role_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseRoleDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseRoleDelete) ProtoMessage() {}

func (x *ApiResponseRoleDelete) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseRoleDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseRoleDelete) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponseRoleDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseRoleDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RoleUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRoleId    int32                  `protobuf:"varint,1,opt,name=user_role_id,json=userRoleId,proto3" json:"user_role_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        int32                  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleUserResponse) Reset() {
	*x = RoleUserResponse{}
	mi := &file_role_role_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleUserResponse) ProtoMessage() {}

func (x *RoleUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleUserResponse.ProtoReflect.Descriptor instead.
func (*RoleUserResponse) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{12}
}

func (x *RoleUserResponse) GetUserRoleId() int32 {
	if x != nil {
		return x.UserRoleId
	}
	return 0
}

func (x *RoleUserResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoleUserResponse) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type ApiResponseRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *RoleResponse          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseRole) Reset() {
	*x = ApiResponseRole{}
	mi := &file_role_role_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseRole) ProtoMessage() {}

func (x *ApiResponseRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseRole.ProtoReflect.Descriptor instead.
func (*ApiResponseRole) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{13}
}

func (x *ApiResponseRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseRole) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseRole) GetData() *RoleResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseUserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *RoleUserResponse      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseUserRole) Reset() {
	*x = ApiResponseUserRole{}
	mi := &file_role_role_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseUserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseUserRole) ProtoMessage() {}

func (x *ApiResponseUserRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseUserRole.ProtoReflect.Descriptor instead.
func (*ApiResponseUserRole) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{14}
}

func (x *ApiResponseUserRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseUserRole) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseUserRole) GetData() *RoleUserResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*RoleResponse        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesRole) Reset() {
	*x = ApiResponsesRole{}
	mi := &file_role_role_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesRole) ProtoMessage() {}

func (x *ApiResponsesRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesRole.ProtoReflect.Descriptor instead.
func (*ApiResponsesRole) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{15}
}

func (x *ApiResponsesRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesRole) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesRole) GetData() []*RoleResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsePaginationRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*RoleResponse        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMeta `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationRole) Reset() {
	*x = ApiResponsePaginationRole{}
	mi := &file_role_role_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationRole) ProtoMessage() {}

func (x *ApiResponsePaginationRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationRole.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationRole) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{16}
}

func (x *ApiResponsePaginationRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationRole) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationRole) GetData() []*RoleResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationRole) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationRoleDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*RoleResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMeta  `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationRoleDeleteAt) Reset() {
	*x = ApiResponsePaginationRoleDeleteAt{}
	mi := &file_role_role_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationRoleDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationRoleDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationRoleDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationRoleDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationRoleDeleteAt) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{17}
}

func (x *ApiResponsePaginationRoleDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationRoleDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationRoleDeleteAt) GetData() []*RoleResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationRoleDeleteAt) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_role_role_common_proto protoreflect.FileDescriptor

const file_role_role_common_proto_rawDesc = "" +
	"\n" +
	"\x16role/role_common.proto\x12\apb.role\x1a\x10common/api.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"]\n" +
	"\x12FindAllRoleRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\".\n" +
	"\x13FindByIdRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x05R\x06roleId\"2\n" +
	"\x17FindByIdUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"+\n" +
	"\x15FindByNameRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x17AssignRoleToUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"M\n" +
	"\x19RemoveRoleFromUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"'\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"p\n" +
	"\fRoleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"\x97\x01\n" +
	"\x14RoleResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\tR\tdeletedAt\"F\n" +
	"\x12ApiResponseRoleAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x15ApiResponseRoleDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"f\n" +
	"\x10RoleUserResponse\x12 \n" +
	"\fuser_role_id\x18\x01 \x01(\x05R\n" +
	"userRoleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x05R\x06roleId\"n\n" +
	"\x0fApiResponseRole\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.pb.role.RoleResponseR\x04data\"v\n" +
	"\x13ApiResponseUserRole\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.pb.role.RoleUserResponseR\x04data\"o\n" +
	"\x10ApiResponsesRole\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.pb.role.RoleResponseR\x04data\"\xb3\x01\n" +
	"\x19ApiResponsePaginationRole\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.pb.role.RoleResponseR\x04data\x129\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\n" +
	"pagination\"\xc3\x01\n" +
	"!ApiResponsePaginationRoleDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.role.RoleResponseDeleteAtR\x04data\x129\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\n" +
	"paginationB=Z;github.com/MamangRust/monolith-point-of-sale-pb/roles;rolesb\x06proto3"

var (
	file_role_role_common_proto_rawDescOnce sync.Once
	file_role_role_common_proto_rawDescData []byte
)

func file_role_role_common_proto_rawDescGZIP() []byte {
	file_role_role_common_proto_rawDescOnce.Do(func() {
		file_role_role_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_role_common_proto_rawDesc), len(file_role_role_common_proto_rawDesc)))
	})
	return file_role_role_common_proto_rawDescData
}

var file_role_role_common_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_role_role_common_proto_goTypes = []any{
	(*FindAllRoleRequest)(nil),                // 0: pb.role.FindAllRoleRequest
	(*FindByIdRoleRequest)(nil),               // 1: pb.role.FindByIdRoleRequest
	(*FindByIdUserRoleRequest)(nil),           // 2: pb.role.FindByIdUserRoleRequest
	(*FindByNameRoleRequest)(nil),             // 3: pb.role.FindByNameRoleRequest
	(*AssignRoleToUserRequest)(nil),           // 4: pb.role.AssignRoleToUserRequest
	(*RemoveRoleFromUserRequest)(nil),         // 5: pb.role.RemoveRoleFromUserRequest
	(*CreateRoleRequest)(nil),                 // 6: pb.role.CreateRoleRequest
	(*UpdateRoleRequest)(nil),                 // 7: pb.role.UpdateRoleRequest
	(*RoleResponse)(nil),                      // 8: pb.role.RoleResponse
	(*RoleResponseDeleteAt)(nil),              // 9: pb.role.RoleResponseDeleteAt
	(*ApiResponseRoleAll)(nil),                // 10: pb.role.ApiResponseRoleAll
	(*ApiResponseRoleDelete)(nil),             // 11: pb.role.ApiResponseRoleDelete
	(*RoleUserResponse)(nil),                  // 12: pb.role.RoleUserResponse
	(*ApiResponseRole)(nil),                   // 13: pb.role.ApiResponseRole
	(*ApiResponseUserRole)(nil),               // 14: pb.role.ApiResponseUserRole
	(*ApiResponsesRole)(nil),                  // 15: pb.role.ApiResponsesRole
	(*ApiResponsePaginationRole)(nil),         // 16: pb.role.ApiResponsePaginationRole
	(*ApiResponsePaginationRoleDeleteAt)(nil), // 17: pb.role.ApiResponsePaginationRoleDeleteAt
	(*common.PaginationMeta)(nil),             // 18: pb.common.PaginationMeta
}
var file_role_role_common_proto_depIdxs = []int32{
	8,  // 0: pb.role.ApiResponseRole.data:type_name -> pb.role.RoleResponse
	12, // 1: pb.role.ApiResponseUserRole.data:type_name -> pb.role.RoleUserResponse
	8,  // 2: pb.role.ApiResponsesRole.data:type_name -> pb.role.RoleResponse
	8,  // 3: pb.role.ApiResponsePaginationRole.data:type_name -> pb.role.RoleResponse
	18, // 4: pb.role.ApiResponsePaginationRole.pagination:type_name -> pb.common.PaginationMeta
	9,  // 5: pb.role.ApiResponsePaginationRoleDeleteAt.data:type_name -> pb.role.RoleResponseDeleteAt
	18, // 6: pb.role.ApiResponsePaginationRoleDeleteAt.pagination:type_name -> pb.common.PaginationMeta
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_role_role_common_proto_init() }
func file_role_role_common_proto_init() {
	if File_role_role_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_role_common_proto_rawDesc), len(file_role_role_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_role_common_proto_goTypes,
		DependencyIndexes: file_role_role_common_proto_depIdxs,
		MessageInfos:      file_role_role_common_proto_msgTypes,
	}.Build()
	File_role_role_common_proto = out.File
	file_role_role_common_proto_goTypes = nil
	file_role_role_common_proto_depIdxs = nil
}
