syntax = "proto3";

package pb.transaction;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "transaction/transaction_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/transactions;transactions";

service TransactionQueryService {
    rpc FindAll(FindAllTransactionRequest) returns (ApiResponsePaginationTransaction);
    rpc FindByMerchant(FindAllTransactionMerchantRequest) returns (ApiResponsePaginationTransaction);
    rpc FindById(FindByIdTransactionRequest) returns (ApiResponseTransaction);
    rpc FindByActive(FindAllTransactionRequest) returns (ApiResponsePaginationTransactionDeleteAt) {}
    rpc FindByTrashed(FindAllTransactionRequest) returns (ApiResponsePaginationTransactionDeleteAt) {}

}
