// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: user/user_command.proto

package users

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_user_command_proto protoreflect.FileDescriptor

const file_user_user_command_proto_rawDesc = "" +
	"\n" +
	"\x17user/user_command.proto\x12\apb.user\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16user/user_common.proto2\xa5\x06\n" +
	"\x12UserCommandService\x12>\n" +
	"\x06Create\x12\x1a.pb.user.CreateUserRequest\x1a\x18.pb.user.ApiResponseUser\x12>\n" +
	"\x06Update\x12\x1a.pb.user.UpdateUserRequest\x1a\x18.pb.user.ApiResponseUser\x12M\n" +
	"\vTrashedUser\x12\x1c.pb.user.FindByIdUserRequest\x1a .pb.user.ApiResponseUserDeleteAt\x12M\n" +
	"\vRestoreUser\x12\x1c.pb.user.FindByIdUserRequest\x1a .pb.user.ApiResponseUserDeleteAt\x12S\n" +
	"\x13DeleteUserPermanent\x12\x1c.pb.user.FindByIdUserRequest\x1a\x1e.pb.user.ApiResponseUserDelete\x12G\n" +
	"\x0eRestoreAllUser\x12\x16.google.protobuf.Empty\x1a\x1b.pb.user.ApiResponseUserAll\"\x00\x12O\n" +
	"\x16DeleteAllUserPermanent\x12\x16.google.protobuf.Empty\x1a\x1b.pb.user.ApiResponseUserAll\"\x00\x12N\n" +
	"\x10CreateUserRecord\x12 .pb.user.CreateUserRecordRequest\x1a\x18.pb.user.ApiResponseUser\x12Z\n" +
	"\x14UpdateUserIsVerified\x12(.pb.user.UpdateUserIsVerifiedUserRequest\x1a\x18.pb.user.ApiResponseUser\x12V\n" +
	"\x12UpdateUserPassword\x12&.pb.user.UpdateUserPasswordUserRequest\x1a\x18.pb.user.ApiResponseUserB=Z;github.com/MamangRust/monolith-point-of-sale-pb/users;usersb\x06proto3"

var file_user_user_command_proto_goTypes = []any{
	(*CreateUserRequest)(nil),               // 0: pb.user.CreateUserRequest
	(*UpdateUserRequest)(nil),               // 1: pb.user.UpdateUserRequest
	(*FindByIdUserRequest)(nil),             // 2: pb.user.FindByIdUserRequest
	(*emptypb.Empty)(nil),                   // 3: google.protobuf.Empty
	(*CreateUserRecordRequest)(nil),         // 4: pb.user.CreateUserRecordRequest
	(*UpdateUserIsVerifiedUserRequest)(nil), // 5: pb.user.UpdateUserIsVerifiedUserRequest
	(*UpdateUserPasswordUserRequest)(nil),   // 6: pb.user.UpdateUserPasswordUserRequest
	(*ApiResponseUser)(nil),                 // 7: pb.user.ApiResponseUser
	(*ApiResponseUserDeleteAt)(nil),         // 8: pb.user.ApiResponseUserDeleteAt
	(*ApiResponseUserDelete)(nil),           // 9: pb.user.ApiResponseUserDelete
	(*ApiResponseUserAll)(nil),              // 10: pb.user.ApiResponseUserAll
}
var file_user_user_command_proto_depIdxs = []int32{
	0,  // 0: pb.user.UserCommandService.Create:input_type -> pb.user.CreateUserRequest
	1,  // 1: pb.user.UserCommandService.Update:input_type -> pb.user.UpdateUserRequest
	2,  // 2: pb.user.UserCommandService.TrashedUser:input_type -> pb.user.FindByIdUserRequest
	2,  // 3: pb.user.UserCommandService.RestoreUser:input_type -> pb.user.FindByIdUserRequest
	2,  // 4: pb.user.UserCommandService.DeleteUserPermanent:input_type -> pb.user.FindByIdUserRequest
	3,  // 5: pb.user.UserCommandService.RestoreAllUser:input_type -> google.protobuf.Empty
	3,  // 6: pb.user.UserCommandService.DeleteAllUserPermanent:input_type -> google.protobuf.Empty
	4,  // 7: pb.user.UserCommandService.CreateUserRecord:input_type -> pb.user.CreateUserRecordRequest
	5,  // 8: pb.user.UserCommandService.UpdateUserIsVerified:input_type -> pb.user.UpdateUserIsVerifiedUserRequest
	6,  // 9: pb.user.UserCommandService.UpdateUserPassword:input_type -> pb.user.UpdateUserPasswordUserRequest
	7,  // 10: pb.user.UserCommandService.Create:output_type -> pb.user.ApiResponseUser
	7,  // 11: pb.user.UserCommandService.Update:output_type -> pb.user.ApiResponseUser
	8,  // 12: pb.user.UserCommandService.TrashedUser:output_type -> pb.user.ApiResponseUserDeleteAt
	8,  // 13: pb.user.UserCommandService.RestoreUser:output_type -> pb.user.ApiResponseUserDeleteAt
	9,  // 14: pb.user.UserCommandService.DeleteUserPermanent:output_type -> pb.user.ApiResponseUserDelete
	10, // 15: pb.user.UserCommandService.RestoreAllUser:output_type -> pb.user.ApiResponseUserAll
	10, // 16: pb.user.UserCommandService.DeleteAllUserPermanent:output_type -> pb.user.ApiResponseUserAll
	7,  // 17: pb.user.UserCommandService.CreateUserRecord:output_type -> pb.user.ApiResponseUser
	7,  // 18: pb.user.UserCommandService.UpdateUserIsVerified:output_type -> pb.user.ApiResponseUser
	7,  // 19: pb.user.UserCommandService.UpdateUserPassword:output_type -> pb.user.ApiResponseUser
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_command_proto_init() }
func file_user_user_command_proto_init() {
	if File_user_user_command_proto != nil {
		return
	}
	file_user_user_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_command_proto_rawDesc), len(file_user_user_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_command_proto_goTypes,
		DependencyIndexes: file_user_user_command_proto_depIdxs,
	}.Build()
	File_user_user_command_proto = out.File
	file_user_user_command_proto_goTypes = nil
	file_user_user_command_proto_depIdxs = nil
}
