// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: user/user_query.proto

package users

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_user_query_proto protoreflect.FileDescriptor

const file_user_user_query_proto_rawDesc = "" +
	"\n" +
	"\x15user/user_query.proto\x12\apb.user\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16user/user_common.proto2\xee\x04\n" +
	"\x10UserQueryService\x12J\n" +
	"\aFindAll\x12\x1b.pb.user.FindAllUserRequest\x1a\".pb.user.ApiResponsePaginationUser\x12B\n" +
	"\bFindById\x12\x1c.pb.user.FindByIdUserRequest\x1a\x18.pb.user.ApiResponseUser\x12Y\n" +
	"\fFindByActive\x12\x1b.pb.user.FindAllUserRequest\x1a*.pb.user.ApiResponsePaginationUserDeleteAt\"\x00\x12Z\n" +
	"\rFindByTrashed\x12\x1b.pb.user.FindAllUserRequest\x1a*.pb.user.ApiResponsePaginationUserDeleteAt\"\x00\x12T\n" +
	"\vFindByEmail\x12\x1f.pb.user.FindByEmailUserRequest\x1a$.pb.user.ApiResponseUserWithPassword\x12]\n" +
	"\x14FindByEmailAndVerify\x12\x1f.pb.user.FindByEmailUserRequest\x1a$.pb.user.ApiResponseUserWithPassword\x12^\n" +
	"\x16FindByVerificationCode\x12*.pb.user.FindByVerificationCodeUserRequest\x1a\x18.pb.user.ApiResponseUserB=Z;github.com/MamangRust/monolith-point-of-sale-pb/users;usersb\x06proto3"

var file_user_user_query_proto_goTypes = []any{
	(*FindAllUserRequest)(nil),                // 0: pb.user.FindAllUserRequest
	(*FindByIdUserRequest)(nil),               // 1: pb.user.FindByIdUserRequest
	(*FindByEmailUserRequest)(nil),            // 2: pb.user.FindByEmailUserRequest
	(*FindByVerificationCodeUserRequest)(nil), // 3: pb.user.FindByVerificationCodeUserRequest
	(*ApiResponsePaginationUser)(nil),         // 4: pb.user.ApiResponsePaginationUser
	(*ApiResponseUser)(nil),                   // 5: pb.user.ApiResponseUser
	(*ApiResponsePaginationUserDeleteAt)(nil), // 6: pb.user.ApiResponsePaginationUserDeleteAt
	(*ApiResponseUserWithPassword)(nil),       // 7: pb.user.ApiResponseUserWithPassword
}
var file_user_user_query_proto_depIdxs = []int32{
	0, // 0: pb.user.UserQueryService.FindAll:input_type -> pb.user.FindAllUserRequest
	1, // 1: pb.user.UserQueryService.FindById:input_type -> pb.user.FindByIdUserRequest
	0, // 2: pb.user.UserQueryService.FindByActive:input_type -> pb.user.FindAllUserRequest
	0, // 3: pb.user.UserQueryService.FindByTrashed:input_type -> pb.user.FindAllUserRequest
	2, // 4: pb.user.UserQueryService.FindByEmail:input_type -> pb.user.FindByEmailUserRequest
	2, // 5: pb.user.UserQueryService.FindByEmailAndVerify:input_type -> pb.user.FindByEmailUserRequest
	3, // 6: pb.user.UserQueryService.FindByVerificationCode:input_type -> pb.user.FindByVerificationCodeUserRequest
	4, // 7: pb.user.UserQueryService.FindAll:output_type -> pb.user.ApiResponsePaginationUser
	5, // 8: pb.user.UserQueryService.FindById:output_type -> pb.user.ApiResponseUser
	6, // 9: pb.user.UserQueryService.FindByActive:output_type -> pb.user.ApiResponsePaginationUserDeleteAt
	6, // 10: pb.user.UserQueryService.FindByTrashed:output_type -> pb.user.ApiResponsePaginationUserDeleteAt
	7, // 11: pb.user.UserQueryService.FindByEmail:output_type -> pb.user.ApiResponseUserWithPassword
	7, // 12: pb.user.UserQueryService.FindByEmailAndVerify:output_type -> pb.user.ApiResponseUserWithPassword
	5, // 13: pb.user.UserQueryService.FindByVerificationCode:output_type -> pb.user.ApiResponseUser
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_query_proto_init() }
func file_user_user_query_proto_init() {
	if File_user_user_query_proto != nil {
		return
	}
	file_user_user_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_query_proto_rawDesc), len(file_user_user_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_query_proto_goTypes,
		DependencyIndexes: file_user_user_query_proto_depIdxs,
	}.Build()
	File_user_user_query_proto = out.File
	file_user_user_query_proto_goTypes = nil
	file_user_user_query_proto_depIdxs = nil
}
