apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- alertmanager-config.yaml
- alertmanager-deployment.yaml
- grafana-deployment.yaml
- grafana-datasource-configmap.yaml
- grafana-service.yaml
- jaeger-deployment.yaml
- jaeger-service.yaml
- logs-pv.yaml
- logs-pvc.yaml
- loki-configmaps.yaml
- loki-deployment.yaml
- loki-pv.yaml
- loki-pvc.yaml
- loki-service.yaml
- node-exporter-deployment.yaml
- node-exporter-service.yaml
- otel-collector-configmap.yaml
- otel-collector-deployment.yaml
- otel-collector-service.yaml
- prometheus-configmap.yaml
- prometheus-rules-configmap.yaml
- prometheus-deployment.yaml
- prometheus.yaml
