syntax = "proto3";

package pb.category.stats;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "category/category_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/categories;categories";

service CategoryStatsByMerchantService {
    rpc FindMonthlyTotalPricesByMerchant(FindYearMonthTotalPriceByMerchant) returns (ApiResponseCategoryMonthlyTotalPrice){}
    rpc FindYearlyTotalPricesByMerchant(FindYearTotalPriceByMerchant) returns (ApiResponseCategoryYearlyTotalPrice){}
    rpc FindMonthPriceByMerchant(FindYearCategoryByMerchant) returns(ApiResponseCategoryMonthPrice);
    rpc FindYearPriceByMerchant(FindYearCategoryByMerchant) returns(ApiResponseCategoryYearPrice);
}
