syntax = "proto3";

package pb.category.stats;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "category/category_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/categories;categories";

service CategoryStatsByIdService {
    rpc FindMonthlyTotalPricesById(FindYearMonthTotalPriceById) returns (ApiResponseCategoryMonthlyTotalPrice){}
    rpc FindYearlyTotalPricesById(FindYearTotalPriceById) returns (ApiResponseCategoryYearlyTotalPrice){}
    rpc FindMonthPriceById(FindYearCategoryById) returns(ApiResponseCategoryMonthPrice);
    rpc FindYearPriceById(FindYearCategoryById) returns(ApiResponseCategoryYearPrice);
}
