// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: category/category_command.proto

package categories

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_category_category_command_proto protoreflect.FileDescriptor

const file_category_category_command_proto_rawDesc = "" +
	"\n" +
	"\x1fcategory/category_command.proto\x12\vpb.category\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1ecategory/category_common.proto2\x99\x05\n" +
	"\x16CategoryCommandService\x12N\n" +
	"\x06Create\x12\".pb.category.CreateCategoryRequest\x1a .pb.category.ApiResponseCategory\x12N\n" +
	"\x06Update\x12\".pb.category.UpdateCategoryRequest\x1a .pb.category.ApiResponseCategory\x12a\n" +
	"\x0fTrashedCategory\x12$.pb.category.FindByIdCategoryRequest\x1a(.pb.category.ApiResponseCategoryDeleteAt\x12a\n" +
	"\x0fRestoreCategory\x12$.pb.category.FindByIdCategoryRequest\x1a(.pb.category.ApiResponseCategoryDeleteAt\x12g\n" +
	"\x17DeleteCategoryPermanent\x12$.pb.category.FindByIdCategoryRequest\x1a&.pb.category.ApiResponseCategoryDelete\x12S\n" +
	"\x12RestoreAllCategory\x12\x16.google.protobuf.Empty\x1a#.pb.category.ApiResponseCategoryAll\"\x00\x12[\n" +
	"\x1aDeleteAllCategoryPermanent\x12\x16.google.protobuf.Empty\x1a#.pb.category.ApiResponseCategoryAll\"\x00BGZEgithub.com/MamangRust/monolith-point-of-sale-pb/categories;categoriesb\x06proto3"

var file_category_category_command_proto_goTypes = []any{
	(*CreateCategoryRequest)(nil),       // 0: pb.category.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),       // 1: pb.category.UpdateCategoryRequest
	(*FindByIdCategoryRequest)(nil),     // 2: pb.category.FindByIdCategoryRequest
	(*emptypb.Empty)(nil),               // 3: google.protobuf.Empty
	(*ApiResponseCategory)(nil),         // 4: pb.category.ApiResponseCategory
	(*ApiResponseCategoryDeleteAt)(nil), // 5: pb.category.ApiResponseCategoryDeleteAt
	(*ApiResponseCategoryDelete)(nil),   // 6: pb.category.ApiResponseCategoryDelete
	(*ApiResponseCategoryAll)(nil),      // 7: pb.category.ApiResponseCategoryAll
}
var file_category_category_command_proto_depIdxs = []int32{
	0, // 0: pb.category.CategoryCommandService.Create:input_type -> pb.category.CreateCategoryRequest
	1, // 1: pb.category.CategoryCommandService.Update:input_type -> pb.category.UpdateCategoryRequest
	2, // 2: pb.category.CategoryCommandService.TrashedCategory:input_type -> pb.category.FindByIdCategoryRequest
	2, // 3: pb.category.CategoryCommandService.RestoreCategory:input_type -> pb.category.FindByIdCategoryRequest
	2, // 4: pb.category.CategoryCommandService.DeleteCategoryPermanent:input_type -> pb.category.FindByIdCategoryRequest
	3, // 5: pb.category.CategoryCommandService.RestoreAllCategory:input_type -> google.protobuf.Empty
	3, // 6: pb.category.CategoryCommandService.DeleteAllCategoryPermanent:input_type -> google.protobuf.Empty
	4, // 7: pb.category.CategoryCommandService.Create:output_type -> pb.category.ApiResponseCategory
	4, // 8: pb.category.CategoryCommandService.Update:output_type -> pb.category.ApiResponseCategory
	5, // 9: pb.category.CategoryCommandService.TrashedCategory:output_type -> pb.category.ApiResponseCategoryDeleteAt
	5, // 10: pb.category.CategoryCommandService.RestoreCategory:output_type -> pb.category.ApiResponseCategoryDeleteAt
	6, // 11: pb.category.CategoryCommandService.DeleteCategoryPermanent:output_type -> pb.category.ApiResponseCategoryDelete
	7, // 12: pb.category.CategoryCommandService.RestoreAllCategory:output_type -> pb.category.ApiResponseCategoryAll
	7, // 13: pb.category.CategoryCommandService.DeleteAllCategoryPermanent:output_type -> pb.category.ApiResponseCategoryAll
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_category_category_command_proto_init() }
func file_category_category_command_proto_init() {
	if File_category_category_command_proto != nil {
		return
	}
	file_category_category_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_category_command_proto_rawDesc), len(file_category_category_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_category_command_proto_goTypes,
		DependencyIndexes: file_category_category_command_proto_depIdxs,
	}.Build()
	File_category_category_command_proto = out.File
	file_category_category_command_proto_goTypes = nil
	file_category_category_command_proto_depIdxs = nil
}
