// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: category/stats/category_stats.proto

package categories

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategoryStatsService_FindMonthlyTotalPrices_FullMethodName = "/pb.category.stats.CategoryStatsService/FindMonthlyTotalPrices"
	CategoryStatsService_FindYearlyTotalPrices_FullMethodName  = "/pb.category.stats.CategoryStatsService/FindYearlyTotalPrices"
	CategoryStatsService_FindMonthPrice_FullMethodName         = "/pb.category.stats.CategoryStatsService/FindMonthPrice"
	CategoryStatsService_FindYearPrice_FullMethodName          = "/pb.category.stats.CategoryStatsService/FindYearPrice"
)

// CategoryStatsServiceClient is the client API for CategoryStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryStatsServiceClient interface {
	FindMonthlyTotalPrices(ctx context.Context, in *FindYearMonthTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPrices(ctx context.Context, in *FindYearTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error)
	FindYearPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error)
}

type categoryStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryStatsServiceClient(cc grpc.ClientConnInterface) CategoryStatsServiceClient {
	return &categoryStatsServiceClient{cc}
}

func (c *categoryStatsServiceClient) FindMonthlyTotalPrices(ctx context.Context, in *FindYearMonthTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthlyTotalPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearlyTotalPrices(ctx context.Context, in *FindYearTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearlyTotalPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindMonthPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryStatsServiceServer is the server API for CategoryStatsService service.
// All implementations must embed UnimplementedCategoryStatsServiceServer
// for forward compatibility.
type CategoryStatsServiceServer interface {
	FindMonthlyTotalPrices(context.Context, *FindYearMonthTotalPrices) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPrices(context.Context, *FindYearTotalPrices) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryMonthPrice, error)
	FindYearPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryYearPrice, error)
	mustEmbedUnimplementedCategoryStatsServiceServer()
}

// UnimplementedCategoryStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryStatsServiceServer struct{}

func (UnimplementedCategoryStatsServiceServer) FindMonthlyTotalPrices(context.Context, *FindYearMonthTotalPrices) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalPrices not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearlyTotalPrices(context.Context, *FindYearTotalPrices) (*ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalPrices not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindMonthPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryMonthPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthPrice not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryYearPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearPrice not implemented")
}
func (UnimplementedCategoryStatsServiceServer) mustEmbedUnimplementedCategoryStatsServiceServer() {}
func (UnimplementedCategoryStatsServiceServer) testEmbeddedByValue()                              {}

// UnsafeCategoryStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryStatsServiceServer will
// result in compilation errors.
type UnsafeCategoryStatsServiceServer interface {
	mustEmbedUnimplementedCategoryStatsServiceServer()
}

func RegisterCategoryStatsServiceServer(s grpc.ServiceRegistrar, srv CategoryStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedCategoryStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryStatsService_ServiceDesc, srv)
}

func _CategoryStatsService_FindMonthlyTotalPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthlyTotalPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPrices(ctx, req.(*FindYearMonthTotalPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearlyTotalPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearlyTotalPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPrices(ctx, req.(*FindYearTotalPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindMonthPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthPrice(ctx, req.(*FindYearCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearPrice(ctx, req.(*FindYearCategory))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryStatsService_ServiceDesc is the grpc.ServiceDesc for CategoryStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.category.stats.CategoryStatsService",
	HandlerType: (*CategoryStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalPrices",
			Handler:    _CategoryStatsService_FindMonthlyTotalPrices_Handler,
		},
		{
			MethodName: "FindYearlyTotalPrices",
			Handler:    _CategoryStatsService_FindYearlyTotalPrices_Handler,
		},
		{
			MethodName: "FindMonthPrice",
			Handler:    _CategoryStatsService_FindMonthPrice_Handler,
		},
		{
			MethodName: "FindYearPrice",
			Handler:    _CategoryStatsService_FindYearPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "category/stats/category_stats.proto",
}
