// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: category/stats/category_statsbymerchant.proto

package categories

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_FullMethodName = "/pb.category.stats.CategoryStatsByMerchantService/FindMonthlyTotalPricesByMerchant"
	CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_FullMethodName  = "/pb.category.stats.CategoryStatsByMerchantService/FindYearlyTotalPricesByMerchant"
	CategoryStatsByMerchantService_FindMonthPriceByMerchant_FullMethodName         = "/pb.category.stats.CategoryStatsByMerchantService/FindMonthPriceByMerchant"
	CategoryStatsByMerchantService_FindYearPriceByMerchant_FullMethodName          = "/pb.category.stats.CategoryStatsByMerchantService/FindYearPriceByMerchant"
)

// CategoryStatsByMerchantServiceClient is the client API for CategoryStatsByMerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryStatsByMerchantServiceClient interface {
	FindMonthlyTotalPricesByMerchant(ctx context.Context, in *FindYearMonthTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesByMerchant(ctx context.Context, in *FindYearTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error)
}

type categoryStatsByMerchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryStatsByMerchantServiceClient(cc grpc.ClientConnInterface) CategoryStatsByMerchantServiceClient {
	return &categoryStatsByMerchantServiceClient{cc}
}

func (c *categoryStatsByMerchantServiceClient) FindMonthlyTotalPricesByMerchant(ctx context.Context, in *FindYearMonthTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByMerchantServiceClient) FindYearlyTotalPricesByMerchant(ctx context.Context, in *FindYearTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByMerchantServiceClient) FindMonthPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindMonthPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsByMerchantServiceClient) FindYearPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryStatsByMerchantService_FindYearPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryStatsByMerchantServiceServer is the server API for CategoryStatsByMerchantService service.
// All implementations must embed UnimplementedCategoryStatsByMerchantServiceServer
// for forward compatibility.
type CategoryStatsByMerchantServiceServer interface {
	FindMonthlyTotalPricesByMerchant(context.Context, *FindYearMonthTotalPriceByMerchant) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesByMerchant(context.Context, *FindYearTotalPriceByMerchant) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryYearPrice, error)
	mustEmbedUnimplementedCategoryStatsByMerchantServiceServer()
}

// UnimplementedCategoryStatsByMerchantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryStatsByMerchantServiceServer struct{}

func (UnimplementedCategoryStatsByMerchantServiceServer) FindMonthlyTotalPricesByMerchant(context.Context, *FindYearMonthTotalPriceByMerchant) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalPricesByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) FindYearlyTotalPricesByMerchant(context.Context, *FindYearTotalPriceByMerchant) (*ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalPricesByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) FindMonthPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryMonthPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthPriceByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) FindYearPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryYearPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearPriceByMerchant not implemented")
}
func (UnimplementedCategoryStatsByMerchantServiceServer) mustEmbedUnimplementedCategoryStatsByMerchantServiceServer() {
}
func (UnimplementedCategoryStatsByMerchantServiceServer) testEmbeddedByValue() {}

// UnsafeCategoryStatsByMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryStatsByMerchantServiceServer will
// result in compilation errors.
type UnsafeCategoryStatsByMerchantServiceServer interface {
	mustEmbedUnimplementedCategoryStatsByMerchantServiceServer()
}

func RegisterCategoryStatsByMerchantServiceServer(s grpc.ServiceRegistrar, srv CategoryStatsByMerchantServiceServer) {
	// If the following call panics, it indicates UnimplementedCategoryStatsByMerchantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryStatsByMerchantService_ServiceDesc, srv)
}

func _CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalPriceByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthlyTotalPricesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthlyTotalPricesByMerchant(ctx, req.(*FindYearMonthTotalPriceByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalPriceByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearlyTotalPricesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearlyTotalPricesByMerchant(ctx, req.(*FindYearTotalPriceByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByMerchantService_FindMonthPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindMonthPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindMonthPriceByMerchant(ctx, req.(*FindYearCategoryByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsByMerchantService_FindYearPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsByMerchantService_FindYearPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsByMerchantServiceServer).FindYearPriceByMerchant(ctx, req.(*FindYearCategoryByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryStatsByMerchantService_ServiceDesc is the grpc.ServiceDesc for CategoryStatsByMerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryStatsByMerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.category.stats.CategoryStatsByMerchantService",
	HandlerType: (*CategoryStatsByMerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalPricesByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindMonthlyTotalPricesByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyTotalPricesByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindYearlyTotalPricesByMerchant_Handler,
		},
		{
			MethodName: "FindMonthPriceByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindMonthPriceByMerchant_Handler,
		},
		{
			MethodName: "FindYearPriceByMerchant",
			Handler:    _CategoryStatsByMerchantService_FindYearPriceByMerchant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "category/stats/category_statsbymerchant.proto",
}
