apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: email-smtp-egress
  namespace: point-of-sale
spec:
  podSelector:
    matchLabels:
      app: email
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: 587
