syntax = "proto3";

package pb.merchant;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "merchant/merchant_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/merchants;merchants";

service MerchantCommandService {
    rpc Create(CreateMerchantRequest) returns (ApiResponseMerchant);
    rpc Update(UpdateMerchantRequest) returns (ApiResponseMerchant);
    rpc UpdateMerchantStatus(UpdateMerchantStatusRequest) returns(ApiResponseMerchant){}
    rpc TrashedMerchant(FindByIdMerchantRequest) returns (ApiResponseMerchantDeleteAt);
    rpc RestoreMerchant(FindByIdMerchantRequest) returns (ApiResponseMerchant);
    rpc DeleteMerchantPermanent(FindByIdMerchantRequest) returns (ApiResponseMerchantDelete);
    rpc RestoreAllMerchant(google.protobuf.Empty) returns (ApiResponseMerchantAll){}
    rpc DeleteAllMerchantPermanent(google.protobuf.Empty) returns (ApiResponseMerchantAll){}
}
