apiVersion: v1
kind: Service
metadata:
  name: category
  namespace: point-of-sale
spec:
  selector:
    app: category
  ports:
    - name: grpc
      port: 50062
      targetPort: 50062
  type: ClusterIP
