// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: product/product_command.proto

package products

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_product_product_command_proto protoreflect.FileDescriptor

const file_product_product_command_proto_rawDesc = "" +
	"\n" +
	"\x1dproduct/product_command.proto\x12\n" +
	"pb.product\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cproduct/product_common.proto2\xad\x06\n" +
	"\x15ProductCommandService\x12J\n" +
	"\x06Create\x12 .pb.product.CreateProductRequest\x1a\x1e.pb.product.ApiResponseProduct\x12J\n" +
	"\x06Update\x12 .pb.product.UpdateProductRequest\x1a\x1e.pb.product.ApiResponseProduct\x12\\\n" +
	"\x0eTrashedProduct\x12\".pb.product.FindByIdProductRequest\x1a&.pb.product.ApiResponseProductDeleteAt\x12\\\n" +
	"\x0eRestoreProduct\x12\".pb.product.FindByIdProductRequest\x1a&.pb.product.ApiResponseProductDeleteAt\x12b\n" +
	"\x16DeleteProductPermanent\x12\".pb.product.FindByIdProductRequest\x1a$.pb.product.ApiResponseProductDelete\x12P\n" +
	"\x11RestoreAllProduct\x12\x16.google.protobuf.Empty\x1a!.pb.product.ApiResponseProductAll\"\x00\x12X\n" +
	"\x19DeleteAllProductPermanent\x12\x16.google.protobuf.Empty\x1a!.pb.product.ApiResponseProductAll\"\x00\x12W\n" +
	"\x0eDecrementStock\x12%.pb.product.AdjustProductStockRequest\x1a\x1e.pb.product.ApiResponseProduct\x12W\n" +
	"\x0eIncrementStock\x12%.pb.product.AdjustProductStockRequest\x1a\x1e.pb.product.ApiResponseProductBCZAgithub.com/MamangRust/monolith-point-of-sale-pb/products;productsb\x06proto3"

var file_product_product_command_proto_goTypes = []any{
	(*CreateProductRequest)(nil),       // 0: pb.product.CreateProductRequest
	(*UpdateProductRequest)(nil),       // 1: pb.product.UpdateProductRequest
	(*FindByIdProductRequest)(nil),     // 2: pb.product.FindByIdProductRequest
	(*emptypb.Empty)(nil),              // 3: google.protobuf.Empty
	(*AdjustProductStockRequest)(nil),  // 4: pb.product.AdjustProductStockRequest
	(*ApiResponseProduct)(nil),         // 5: pb.product.ApiResponseProduct
	(*ApiResponseProductDeleteAt)(nil), // 6: pb.product.ApiResponseProductDeleteAt
	(*ApiResponseProductDelete)(nil),   // 7: pb.product.ApiResponseProductDelete
	(*ApiResponseProductAll)(nil),      // 8: pb.product.ApiResponseProductAll
}
var file_product_product_command_proto_depIdxs = []int32{
	0, // 0: pb.product.ProductCommandService.Create:input_type -> pb.product.CreateProductRequest
	1, // 1: pb.product.ProductCommandService.Update:input_type -> pb.product.UpdateProductRequest
	2, // 2: pb.product.ProductCommandService.TrashedProduct:input_type -> pb.product.FindByIdProductRequest
	2, // 3: pb.product.ProductCommandService.RestoreProduct:input_type -> pb.product.FindByIdProductRequest
	2, // 4: pb.product.ProductCommandService.DeleteProductPermanent:input_type -> pb.product.FindByIdProductRequest
	3, // 5: pb.product.ProductCommandService.RestoreAllProduct:input_type -> google.protobuf.Empty
	3, // 6: pb.product.ProductCommandService.DeleteAllProductPermanent:input_type -> google.protobuf.Empty
	4, // 7: pb.product.ProductCommandService.DecrementStock:input_type -> pb.product.AdjustProductStockRequest
	4, // 8: pb.product.ProductCommandService.IncrementStock:input_type -> pb.product.AdjustProductStockRequest
	5, // 9: pb.product.ProductCommandService.Create:output_type -> pb.product.ApiResponseProduct
	5, // 10: pb.product.ProductCommandService.Update:output_type -> pb.product.ApiResponseProduct
	6, // 11: pb.product.ProductCommandService.TrashedProduct:output_type -> pb.product.ApiResponseProductDeleteAt
	6, // 12: pb.product.ProductCommandService.RestoreProduct:output_type -> pb.product.ApiResponseProductDeleteAt
	7, // 13: pb.product.ProductCommandService.DeleteProductPermanent:output_type -> pb.product.ApiResponseProductDelete
	8, // 14: pb.product.ProductCommandService.RestoreAllProduct:output_type -> pb.product.ApiResponseProductAll
	8, // 15: pb.product.ProductCommandService.DeleteAllProductPermanent:output_type -> pb.product.ApiResponseProductAll
	5, // 16: pb.product.ProductCommandService.DecrementStock:output_type -> pb.product.ApiResponseProduct
	5, // 17: pb.product.ProductCommandService.IncrementStock:output_type -> pb.product.ApiResponseProduct
	9, // [9:18] is the sub-list for method output_type
	0, // [0:9] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_product_command_proto_init() }
func file_product_product_command_proto_init() {
	if File_product_product_command_proto != nil {
		return
	}
	file_product_product_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_product_command_proto_rawDesc), len(file_product_product_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_product_command_proto_goTypes,
		DependencyIndexes: file_product_product_command_proto_depIdxs,
	}.Build()
	File_product_product_command_proto = out.File
	file_product_product_command_proto_goTypes = nil
	file_product_product_command_proto_depIdxs = nil
}
