// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: product/product_command.proto

package products

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductCommandService_Create_FullMethodName                    = "/pb.product.ProductCommandService/Create"
	ProductCommandService_Update_FullMethodName                    = "/pb.product.ProductCommandService/Update"
	ProductCommandService_TrashedProduct_FullMethodName            = "/pb.product.ProductCommandService/TrashedProduct"
	ProductCommandService_RestoreProduct_FullMethodName            = "/pb.product.ProductCommandService/RestoreProduct"
	ProductCommandService_DeleteProductPermanent_FullMethodName    = "/pb.product.ProductCommandService/DeleteProductPermanent"
	ProductCommandService_RestoreAllProduct_FullMethodName         = "/pb.product.ProductCommandService/RestoreAllProduct"
	ProductCommandService_DeleteAllProductPermanent_FullMethodName = "/pb.product.ProductCommandService/DeleteAllProductPermanent"
	ProductCommandService_DecrementStock_FullMethodName            = "/pb.product.ProductCommandService/DecrementStock"
	ProductCommandService_IncrementStock_FullMethodName            = "/pb.product.ProductCommandService/IncrementStock"
)

// ProductCommandServiceClient is the client API for ProductCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductCommandServiceClient interface {
	Create(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error)
	Update(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error)
	TrashedProduct(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDeleteAt, error)
	RestoreProduct(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDeleteAt, error)
	DeleteProductPermanent(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDelete, error)
	RestoreAllProduct(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseProductAll, error)
	DeleteAllProductPermanent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseProductAll, error)
	DecrementStock(ctx context.Context, in *AdjustProductStockRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error)
	IncrementStock(ctx context.Context, in *AdjustProductStockRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error)
}

type productCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductCommandServiceClient(cc grpc.ClientConnInterface) ProductCommandServiceClient {
	return &productCommandServiceClient{cc}
}

func (c *productCommandServiceClient) Create(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProduct)
	err := c.cc.Invoke(ctx, ProductCommandService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) Update(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProduct)
	err := c.cc.Invoke(ctx, ProductCommandService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) TrashedProduct(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProductDeleteAt)
	err := c.cc.Invoke(ctx, ProductCommandService_TrashedProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) RestoreProduct(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProductDeleteAt)
	err := c.cc.Invoke(ctx, ProductCommandService_RestoreProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) DeleteProductPermanent(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProductDelete)
	err := c.cc.Invoke(ctx, ProductCommandService_DeleteProductPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) RestoreAllProduct(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseProductAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProductAll)
	err := c.cc.Invoke(ctx, ProductCommandService_RestoreAllProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) DeleteAllProductPermanent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseProductAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProductAll)
	err := c.cc.Invoke(ctx, ProductCommandService_DeleteAllProductPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) DecrementStock(ctx context.Context, in *AdjustProductStockRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProduct)
	err := c.cc.Invoke(ctx, ProductCommandService_DecrementStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) IncrementStock(ctx context.Context, in *AdjustProductStockRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProduct)
	err := c.cc.Invoke(ctx, ProductCommandService_IncrementStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductCommandServiceServer is the server API for ProductCommandService service.
// All implementations must embed UnimplementedProductCommandServiceServer
// for forward compatibility.
type ProductCommandServiceServer interface {
	Create(context.Context, *CreateProductRequest) (*ApiResponseProduct, error)
	Update(context.Context, *UpdateProductRequest) (*ApiResponseProduct, error)
	TrashedProduct(context.Context, *FindByIdProductRequest) (*ApiResponseProductDeleteAt, error)
	RestoreProduct(context.Context, *FindByIdProductRequest) (*ApiResponseProductDeleteAt, error)
	DeleteProductPermanent(context.Context, *FindByIdProductRequest) (*ApiResponseProductDelete, error)
	RestoreAllProduct(context.Context, *emptypb.Empty) (*ApiResponseProductAll, error)
	DeleteAllProductPermanent(context.Context, *emptypb.Empty) (*ApiResponseProductAll, error)
	DecrementStock(context.Context, *AdjustProductStockRequest) (*ApiResponseProduct, error)
	IncrementStock(context.Context, *AdjustProductStockRequest) (*ApiResponseProduct, error)
	mustEmbedUnimplementedProductCommandServiceServer()
}

// UnimplementedProductCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductCommandServiceServer struct{}

func (UnimplementedProductCommandServiceServer) Create(context.Context, *CreateProductRequest) (*ApiResponseProduct, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProductCommandServiceServer) Update(context.Context, *UpdateProductRequest) (*ApiResponseProduct, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProductCommandServiceServer) TrashedProduct(context.Context, *FindByIdProductRequest) (*ApiResponseProductDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method TrashedProduct not implemented")
}
func (UnimplementedProductCommandServiceServer) RestoreProduct(context.Context, *FindByIdProductRequest) (*ApiResponseProductDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreProduct not implemented")
}
func (UnimplementedProductCommandServiceServer) DeleteProductPermanent(context.Context, *FindByIdProductRequest) (*ApiResponseProductDelete, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductPermanent not implemented")
}
func (UnimplementedProductCommandServiceServer) RestoreAllProduct(context.Context, *emptypb.Empty) (*ApiResponseProductAll, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreAllProduct not implemented")
}
func (UnimplementedProductCommandServiceServer) DeleteAllProductPermanent(context.Context, *emptypb.Empty) (*ApiResponseProductAll, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAllProductPermanent not implemented")
}
func (UnimplementedProductCommandServiceServer) DecrementStock(context.Context, *AdjustProductStockRequest) (*ApiResponseProduct, error) {
	return nil, status.Error(codes.Unimplemented, "method DecrementStock not implemented")
}
func (UnimplementedProductCommandServiceServer) IncrementStock(context.Context, *AdjustProductStockRequest) (*ApiResponseProduct, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementStock not implemented")
}
func (UnimplementedProductCommandServiceServer) mustEmbedUnimplementedProductCommandServiceServer() {}
func (UnimplementedProductCommandServiceServer) testEmbeddedByValue()                               {}

// UnsafeProductCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductCommandServiceServer will
// result in compilation errors.
type UnsafeProductCommandServiceServer interface {
	mustEmbedUnimplementedProductCommandServiceServer()
}

func RegisterProductCommandServiceServer(s grpc.ServiceRegistrar, srv ProductCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedProductCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductCommandService_ServiceDesc, srv)
}

func _ProductCommandService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).Create(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).Update(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_TrashedProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).TrashedProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_TrashedProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).TrashedProduct(ctx, req.(*FindByIdProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_RestoreProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).RestoreProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_RestoreProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).RestoreProduct(ctx, req.(*FindByIdProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_DeleteProductPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).DeleteProductPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_DeleteProductPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).DeleteProductPermanent(ctx, req.(*FindByIdProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_RestoreAllProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).RestoreAllProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_RestoreAllProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).RestoreAllProduct(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_DeleteAllProductPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).DeleteAllProductPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_DeleteAllProductPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).DeleteAllProductPermanent(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_DecrementStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustProductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).DecrementStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_DecrementStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).DecrementStock(ctx, req.(*AdjustProductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_IncrementStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustProductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).IncrementStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_IncrementStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).IncrementStock(ctx, req.(*AdjustProductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductCommandService_ServiceDesc is the grpc.ServiceDesc for ProductCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.product.ProductCommandService",
	HandlerType: (*ProductCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProductCommandService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProductCommandService_Update_Handler,
		},
		{
			MethodName: "TrashedProduct",
			Handler:    _ProductCommandService_TrashedProduct_Handler,
		},
		{
			MethodName: "RestoreProduct",
			Handler:    _ProductCommandService_RestoreProduct_Handler,
		},
		{
			MethodName: "DeleteProductPermanent",
			Handler:    _ProductCommandService_DeleteProductPermanent_Handler,
		},
		{
			MethodName: "RestoreAllProduct",
			Handler:    _ProductCommandService_RestoreAllProduct_Handler,
		},
		{
			MethodName: "DeleteAllProductPermanent",
			Handler:    _ProductCommandService_DeleteAllProductPermanent_Handler,
		},
		{
			MethodName: "DecrementStock",
			Handler:    _ProductCommandService_DecrementStock_Handler,
		},
		{
			MethodName: "IncrementStock",
			Handler:    _ProductCommandService_IncrementStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product/product_command.proto",
}
