// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: product/product_query.proto

package products

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_product_product_query_proto protoreflect.FileDescriptor

const file_product_product_query_proto_rawDesc = "" +
	"\n" +
	"\x1bproduct/product_query.proto\x12\n" +
	"pb.product\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cproduct/product_common.proto2\xda\x04\n" +
	"\x13ProductQueryService\x12V\n" +
	"\aFindAll\x12!.pb.product.FindAllProductRequest\x1a(.pb.product.ApiResponsePaginationProduct\x12e\n" +
	"\x0eFindByMerchant\x12).pb.product.FindAllProductMerchantRequest\x1a(.pb.product.ApiResponsePaginationProduct\x12e\n" +
	"\x0eFindByCategory\x12).pb.product.FindAllProductCategoryRequest\x1a(.pb.product.ApiResponsePaginationProduct\x12N\n" +
	"\bFindById\x12\".pb.product.FindByIdProductRequest\x1a\x1e.pb.product.ApiResponseProduct\x12e\n" +
	"\fFindByActive\x12!.pb.product.FindAllProductRequest\x1a0.pb.product.ApiResponsePaginationProductDeleteAt\"\x00\x12f\n" +
	"\rFindByTrashed\x12!.pb.product.FindAllProductRequest\x1a0.pb.product.ApiResponsePaginationProductDeleteAt\"\x00BCZAgithub.com/MamangRust/monolith-point-of-sale-pb/products;productsb\x06proto3"

var file_product_product_query_proto_goTypes = []any{
	(*FindAllProductRequest)(nil),                // 0: pb.product.FindAllProductRequest
	(*FindAllProductMerchantRequest)(nil),        // 1: pb.product.FindAllProductMerchantRequest
	(*FindAllProductCategoryRequest)(nil),        // 2: pb.product.FindAllProductCategoryRequest
	(*FindByIdProductRequest)(nil),               // 3: pb.product.FindByIdProductRequest
	(*ApiResponsePaginationProduct)(nil),         // 4: pb.product.ApiResponsePaginationProduct
	(*ApiResponseProduct)(nil),                   // 5: pb.product.ApiResponseProduct
	(*ApiResponsePaginationProductDeleteAt)(nil), // 6: pb.product.ApiResponsePaginationProductDeleteAt
}
var file_product_product_query_proto_depIdxs = []int32{
	0, // 0: pb.product.ProductQueryService.FindAll:input_type -> pb.product.FindAllProductRequest
	1, // 1: pb.product.ProductQueryService.FindByMerchant:input_type -> pb.product.FindAllProductMerchantRequest
	2, // 2: pb.product.ProductQueryService.FindByCategory:input_type -> pb.product.FindAllProductCategoryRequest
	3, // 3: pb.product.ProductQueryService.FindById:input_type -> pb.product.FindByIdProductRequest
	0, // 4: pb.product.ProductQueryService.FindByActive:input_type -> pb.product.FindAllProductRequest
	0, // 5: pb.product.ProductQueryService.FindByTrashed:input_type -> pb.product.FindAllProductRequest
	4, // 6: pb.product.ProductQueryService.FindAll:output_type -> pb.product.ApiResponsePaginationProduct
	4, // 7: pb.product.ProductQueryService.FindByMerchant:output_type -> pb.product.ApiResponsePaginationProduct
	4, // 8: pb.product.ProductQueryService.FindByCategory:output_type -> pb.product.ApiResponsePaginationProduct
	5, // 9: pb.product.ProductQueryService.FindById:output_type -> pb.product.ApiResponseProduct
	6, // 10: pb.product.ProductQueryService.FindByActive:output_type -> pb.product.ApiResponsePaginationProductDeleteAt
	6, // 11: pb.product.ProductQueryService.FindByTrashed:output_type -> pb.product.ApiResponsePaginationProductDeleteAt
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_product_query_proto_init() }
func file_product_product_query_proto_init() {
	if File_product_product_query_proto != nil {
		return
	}
	file_product_product_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_product_query_proto_rawDesc), len(file_product_product_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_product_query_proto_goTypes,
		DependencyIndexes: file_product_product_query_proto_depIdxs,
	}.Build()
	File_product_product_query_proto = out.File
	file_product_product_query_proto_goTypes = nil
	file_product_product_query_proto_depIdxs = nil
}
