syntax = "proto3";

package pb.cashier;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "cashier/cashier_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/cashiers;cashiers";

service CashierQueryService {
    rpc FindAll(FindAllCashierRequest) returns (ApiResponsePaginationCashier){}
    rpc FindById(FindByIdCashierRequest) returns (ApiResponseCashier){}
    rpc FindByActive(FindAllCashierRequest) returns (ApiResponsePaginationCashierDeleteAt) {}
    rpc FindByMerchant(FindByMerchantCashierRequest) returns (ApiResponsePaginationCashier){}
    rpc FindByTrashed(FindAllCashierRequest) returns (ApiResponsePaginationCashierDeleteAt) {}

}
