// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: order/stats/order_statsbyid.proto

package orders

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_order_stats_order_statsbyid_proto protoreflect.FileDescriptor

const file_order_stats_order_statsbyid_proto_rawDesc = "" +
	"\n" +
	"!order/stats/order_statsbyid.proto\x12\x0epb.order.stats\x1a\x10common/api.proto\x1a\x18order/order_common.proto2\x82\x02\n" +
	"\x15OrderStatsByIdService\x12w\n" +
	"\x1bFindMonthlyTotalRevenueById\x12'.pb.order.FindYearMonthTotalRevenueById\x1a-.pb.order.ApiResponseOrderMonthlyTotalRevenue\"\x00\x12p\n" +
	"\x1aFindYearlyTotalRevenueById\x12\".pb.order.FindYearTotalRevenueById\x1a,.pb.order.ApiResponseOrderYearlyTotalRevenue\"\x00B?Z=github.com/MamangRust/monolith-point-of-sale-pb/orders;ordersb\x06proto3"

var file_order_stats_order_statsbyid_proto_goTypes = []any{
	(*FindYearMonthTotalRevenueById)(nil),       // 0: pb.order.FindYearMonthTotalRevenueById
	(*FindYearTotalRevenueById)(nil),            // 1: pb.order.FindYearTotalRevenueById
	(*ApiResponseOrderMonthlyTotalRevenue)(nil), // 2: pb.order.ApiResponseOrderMonthlyTotalRevenue
	(*ApiResponseOrderYearlyTotalRevenue)(nil),  // 3: pb.order.ApiResponseOrderYearlyTotalRevenue
}
var file_order_stats_order_statsbyid_proto_depIdxs = []int32{
	0, // 0: pb.order.stats.OrderStatsByIdService.FindMonthlyTotalRevenueById:input_type -> pb.order.FindYearMonthTotalRevenueById
	1, // 1: pb.order.stats.OrderStatsByIdService.FindYearlyTotalRevenueById:input_type -> pb.order.FindYearTotalRevenueById
	2, // 2: pb.order.stats.OrderStatsByIdService.FindMonthlyTotalRevenueById:output_type -> pb.order.ApiResponseOrderMonthlyTotalRevenue
	3, // 3: pb.order.stats.OrderStatsByIdService.FindYearlyTotalRevenueById:output_type -> pb.order.ApiResponseOrderYearlyTotalRevenue
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_stats_order_statsbyid_proto_init() }
func file_order_stats_order_statsbyid_proto_init() {
	if File_order_stats_order_statsbyid_proto != nil {
		return
	}
	file_order_order_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_stats_order_statsbyid_proto_rawDesc), len(file_order_stats_order_statsbyid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_stats_order_statsbyid_proto_goTypes,
		DependencyIndexes: file_order_stats_order_statsbyid_proto_depIdxs,
	}.Build()
	File_order_stats_order_statsbyid_proto = out.File
	file_order_stats_order_statsbyid_proto_goTypes = nil
	file_order_stats_order_statsbyid_proto_depIdxs = nil
}
