// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: order/stats/order_stats.proto

package orders

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_order_stats_order_stats_proto protoreflect.FileDescriptor

const file_order_stats_order_stats_proto_rawDesc = "" +
	"\n" +
	"\x1dorder/stats/order_stats.proto\x12\x0epb.order.stats\x1a\x10common/api.proto\x1a\x18order/order_common.proto2\x90\x03\n" +
	"\x11OrderStatsService\x12o\n" +
	"\x17FindMonthlyTotalRevenue\x12#.pb.order.FindYearMonthTotalRevenue\x1a-.pb.order.ApiResponseOrderMonthlyTotalRevenue\"\x00\x12h\n" +
	"\x16FindYearlyTotalRevenue\x12\x1e.pb.order.FindYearTotalRevenue\x1a,.pb.order.ApiResponseOrderYearlyTotalRevenue\"\x00\x12P\n" +
	"\x12FindMonthlyRevenue\x12\x17.pb.order.FindYearOrder\x1a!.pb.order.ApiResponseOrderMonthly\x12N\n" +
	"\x11FindYearlyRevenue\x12\x17.pb.order.FindYearOrder\x1a .pb.order.ApiResponseOrderYearlyB?Z=github.com/MamangRust/monolith-point-of-sale-pb/orders;ordersb\x06proto3"

var file_order_stats_order_stats_proto_goTypes = []any{
	(*FindYearMonthTotalRevenue)(nil),           // 0: pb.order.FindYearMonthTotalRevenue
	(*FindYearTotalRevenue)(nil),                // 1: pb.order.FindYearTotalRevenue
	(*FindYearOrder)(nil),                       // 2: pb.order.FindYearOrder
	(*ApiResponseOrderMonthlyTotalRevenue)(nil), // 3: pb.order.ApiResponseOrderMonthlyTotalRevenue
	(*ApiResponseOrderYearlyTotalRevenue)(nil),  // 4: pb.order.ApiResponseOrderYearlyTotalRevenue
	(*ApiResponseOrderMonthly)(nil),             // 5: pb.order.ApiResponseOrderMonthly
	(*ApiResponseOrderYearly)(nil),              // 6: pb.order.ApiResponseOrderYearly
}
var file_order_stats_order_stats_proto_depIdxs = []int32{
	0, // 0: pb.order.stats.OrderStatsService.FindMonthlyTotalRevenue:input_type -> pb.order.FindYearMonthTotalRevenue
	1, // 1: pb.order.stats.OrderStatsService.FindYearlyTotalRevenue:input_type -> pb.order.FindYearTotalRevenue
	2, // 2: pb.order.stats.OrderStatsService.FindMonthlyRevenue:input_type -> pb.order.FindYearOrder
	2, // 3: pb.order.stats.OrderStatsService.FindYearlyRevenue:input_type -> pb.order.FindYearOrder
	3, // 4: pb.order.stats.OrderStatsService.FindMonthlyTotalRevenue:output_type -> pb.order.ApiResponseOrderMonthlyTotalRevenue
	4, // 5: pb.order.stats.OrderStatsService.FindYearlyTotalRevenue:output_type -> pb.order.ApiResponseOrderYearlyTotalRevenue
	5, // 6: pb.order.stats.OrderStatsService.FindMonthlyRevenue:output_type -> pb.order.ApiResponseOrderMonthly
	6, // 7: pb.order.stats.OrderStatsService.FindYearlyRevenue:output_type -> pb.order.ApiResponseOrderYearly
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_stats_order_stats_proto_init() }
func file_order_stats_order_stats_proto_init() {
	if File_order_stats_order_stats_proto != nil {
		return
	}
	file_order_order_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_stats_order_stats_proto_rawDesc), len(file_order_stats_order_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_stats_order_stats_proto_goTypes,
		DependencyIndexes: file_order_stats_order_stats_proto_depIdxs,
	}.Build()
	File_order_stats_order_stats_proto = out.File
	file_order_stats_order_stats_proto_goTypes = nil
	file_order_stats_order_stats_proto_depIdxs = nil
}
