// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: order/stats/order_statsbymerchant.proto

package orders

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderStatsByMerchantService_FindMonthlyTotalRevenueByMerchant_FullMethodName = "/pb.order.stats.OrderStatsByMerchantService/FindMonthlyTotalRevenueByMerchant"
	OrderStatsByMerchantService_FindYearlyTotalRevenueByMerchant_FullMethodName  = "/pb.order.stats.OrderStatsByMerchantService/FindYearlyTotalRevenueByMerchant"
	OrderStatsByMerchantService_FindMonthlyRevenueByMerchant_FullMethodName      = "/pb.order.stats.OrderStatsByMerchantService/FindMonthlyRevenueByMerchant"
	OrderStatsByMerchantService_FindYearlyRevenueByMerchant_FullMethodName       = "/pb.order.stats.OrderStatsByMerchantService/FindYearlyRevenueByMerchant"
)

// OrderStatsByMerchantServiceClient is the client API for OrderStatsByMerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderStatsByMerchantServiceClient interface {
	FindMonthlyTotalRevenueByMerchant(ctx context.Context, in *FindYearMonthTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueByMerchant(ctx context.Context, in *FindYearTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthly, error)
	FindYearlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearly, error)
}

type orderStatsByMerchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderStatsByMerchantServiceClient(cc grpc.ClientConnInterface) OrderStatsByMerchantServiceClient {
	return &orderStatsByMerchantServiceClient{cc}
}

func (c *orderStatsByMerchantServiceClient) FindMonthlyTotalRevenueByMerchant(ctx context.Context, in *FindYearMonthTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsByMerchantService_FindMonthlyTotalRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsByMerchantServiceClient) FindYearlyTotalRevenueByMerchant(ctx context.Context, in *FindYearTotalRevenueByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearlyTotalRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearlyTotalRevenue)
	err := c.cc.Invoke(ctx, OrderStatsByMerchantService_FindYearlyTotalRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsByMerchantServiceClient) FindMonthlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderMonthly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthly)
	err := c.cc.Invoke(ctx, OrderStatsByMerchantService_FindMonthlyRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsByMerchantServiceClient) FindYearlyRevenueByMerchant(ctx context.Context, in *FindYearOrderByMerchant, opts ...grpc.CallOption) (*ApiResponseOrderYearly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearly)
	err := c.cc.Invoke(ctx, OrderStatsByMerchantService_FindYearlyRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderStatsByMerchantServiceServer is the server API for OrderStatsByMerchantService service.
// All implementations must embed UnimplementedOrderStatsByMerchantServiceServer
// for forward compatibility.
type OrderStatsByMerchantServiceServer interface {
	FindMonthlyTotalRevenueByMerchant(context.Context, *FindYearMonthTotalRevenueByMerchant) (*ApiResponseOrderMonthlyTotalRevenue, error)
	FindYearlyTotalRevenueByMerchant(context.Context, *FindYearTotalRevenueByMerchant) (*ApiResponseOrderYearlyTotalRevenue, error)
	FindMonthlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderMonthly, error)
	FindYearlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderYearly, error)
	mustEmbedUnimplementedOrderStatsByMerchantServiceServer()
}

// UnimplementedOrderStatsByMerchantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderStatsByMerchantServiceServer struct{}

func (UnimplementedOrderStatsByMerchantServiceServer) FindMonthlyTotalRevenueByMerchant(context.Context, *FindYearMonthTotalRevenueByMerchant) (*ApiResponseOrderMonthlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsByMerchantServiceServer) FindYearlyTotalRevenueByMerchant(context.Context, *FindYearTotalRevenueByMerchant) (*ApiResponseOrderYearlyTotalRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsByMerchantServiceServer) FindMonthlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderMonthly, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsByMerchantServiceServer) FindYearlyRevenueByMerchant(context.Context, *FindYearOrderByMerchant) (*ApiResponseOrderYearly, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyRevenueByMerchant not implemented")
}
func (UnimplementedOrderStatsByMerchantServiceServer) mustEmbedUnimplementedOrderStatsByMerchantServiceServer() {
}
func (UnimplementedOrderStatsByMerchantServiceServer) testEmbeddedByValue() {}

// UnsafeOrderStatsByMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderStatsByMerchantServiceServer will
// result in compilation errors.
type UnsafeOrderStatsByMerchantServiceServer interface {
	mustEmbedUnimplementedOrderStatsByMerchantServiceServer()
}

func RegisterOrderStatsByMerchantServiceServer(s grpc.ServiceRegistrar, srv OrderStatsByMerchantServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderStatsByMerchantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderStatsByMerchantService_ServiceDesc, srv)
}

func _OrderStatsByMerchantService_FindMonthlyTotalRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalRevenueByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsByMerchantServiceServer).FindMonthlyTotalRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsByMerchantService_FindMonthlyTotalRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsByMerchantServiceServer).FindMonthlyTotalRevenueByMerchant(ctx, req.(*FindYearMonthTotalRevenueByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsByMerchantService_FindYearlyTotalRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalRevenueByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsByMerchantServiceServer).FindYearlyTotalRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsByMerchantService_FindYearlyTotalRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsByMerchantServiceServer).FindYearlyTotalRevenueByMerchant(ctx, req.(*FindYearTotalRevenueByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsByMerchantService_FindMonthlyRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearOrderByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsByMerchantServiceServer).FindMonthlyRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsByMerchantService_FindMonthlyRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsByMerchantServiceServer).FindMonthlyRevenueByMerchant(ctx, req.(*FindYearOrderByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsByMerchantService_FindYearlyRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearOrderByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsByMerchantServiceServer).FindYearlyRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsByMerchantService_FindYearlyRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsByMerchantServiceServer).FindYearlyRevenueByMerchant(ctx, req.(*FindYearOrderByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderStatsByMerchantService_ServiceDesc is the grpc.ServiceDesc for OrderStatsByMerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderStatsByMerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.order.stats.OrderStatsByMerchantService",
	HandlerType: (*OrderStatsByMerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalRevenueByMerchant",
			Handler:    _OrderStatsByMerchantService_FindMonthlyTotalRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyTotalRevenueByMerchant",
			Handler:    _OrderStatsByMerchantService_FindYearlyTotalRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindMonthlyRevenueByMerchant",
			Handler:    _OrderStatsByMerchantService_FindMonthlyRevenueByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyRevenueByMerchant",
			Handler:    _OrderStatsByMerchantService_FindYearlyRevenueByMerchant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/stats/order_statsbymerchant.proto",
}
