// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: order/order_query.proto

package orders

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_order_order_query_proto protoreflect.FileDescriptor

const file_order_order_query_proto_rawDesc = "" +
	"\n" +
	"\x17order/order_query.proto\x12\bpb.order\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18order/order_common.proto2\xc9\x03\n" +
	"\x11OrderQueryService\x12N\n" +
	"\aFindAll\x12\x1d.pb.order.FindAllOrderRequest\x1a$.pb.order.ApiResponsePaginationOrder\x12]\n" +
	"\x0eFindByMerchant\x12%.pb.order.FindAllOrderMerchantRequest\x1a$.pb.order.ApiResponsePaginationOrder\x12F\n" +
	"\bFindById\x12\x1e.pb.order.FindByIdOrderRequest\x1a\x1a.pb.order.ApiResponseOrder\x12]\n" +
	"\fFindByActive\x12\x1d.pb.order.FindAllOrderRequest\x1a,.pb.order.ApiResponsePaginationOrderDeleteAt\"\x00\x12^\n" +
	"\rFindByTrashed\x12\x1d.pb.order.FindAllOrderRequest\x1a,.pb.order.ApiResponsePaginationOrderDeleteAt\"\x00B?Z=github.com/MamangRust/monolith-point-of-sale-pb/orders;ordersb\x06proto3"

var file_order_order_query_proto_goTypes = []any{
	(*FindAllOrderRequest)(nil),                // 0: pb.order.FindAllOrderRequest
	(*FindAllOrderMerchantRequest)(nil),        // 1: pb.order.FindAllOrderMerchantRequest
	(*FindByIdOrderRequest)(nil),               // 2: pb.order.FindByIdOrderRequest
	(*ApiResponsePaginationOrder)(nil),         // 3: pb.order.ApiResponsePaginationOrder
	(*ApiResponseOrder)(nil),                   // 4: pb.order.ApiResponseOrder
	(*ApiResponsePaginationOrderDeleteAt)(nil), // 5: pb.order.ApiResponsePaginationOrderDeleteAt
}
var file_order_order_query_proto_depIdxs = []int32{
	0, // 0: pb.order.OrderQueryService.FindAll:input_type -> pb.order.FindAllOrderRequest
	1, // 1: pb.order.OrderQueryService.FindByMerchant:input_type -> pb.order.FindAllOrderMerchantRequest
	2, // 2: pb.order.OrderQueryService.FindById:input_type -> pb.order.FindByIdOrderRequest
	0, // 3: pb.order.OrderQueryService.FindByActive:input_type -> pb.order.FindAllOrderRequest
	0, // 4: pb.order.OrderQueryService.FindByTrashed:input_type -> pb.order.FindAllOrderRequest
	3, // 5: pb.order.OrderQueryService.FindAll:output_type -> pb.order.ApiResponsePaginationOrder
	3, // 6: pb.order.OrderQueryService.FindByMerchant:output_type -> pb.order.ApiResponsePaginationOrder
	4, // 7: pb.order.OrderQueryService.FindById:output_type -> pb.order.ApiResponseOrder
	5, // 8: pb.order.OrderQueryService.FindByActive:output_type -> pb.order.ApiResponsePaginationOrderDeleteAt
	5, // 9: pb.order.OrderQueryService.FindByTrashed:output_type -> pb.order.ApiResponsePaginationOrderDeleteAt
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_order_query_proto_init() }
func file_order_order_query_proto_init() {
	if File_order_order_query_proto != nil {
		return
	}
	file_order_order_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_query_proto_rawDesc), len(file_order_order_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_order_query_proto_goTypes,
		DependencyIndexes: file_order_order_query_proto_depIdxs,
	}.Build()
	File_order_order_query_proto = out.File
	file_order_order_query_proto_goTypes = nil
	file_order_order_query_proto_depIdxs = nil
}
