syntax = "proto3";

package pb.product;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "product/product_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/products;products";

service ProductQueryService {
    rpc FindAll(FindAllProductRequest) returns (ApiResponsePaginationProduct);
    rpc FindByMerchant(FindAllProductMerchantRequest) returns (ApiResponsePaginationProduct);
    rpc FindByCategory(FindAllProductCategoryRequest) returns (ApiResponsePaginationProduct);
    rpc FindById(FindByIdProductRequest) returns (ApiResponseProduct);
    rpc FindByActive(FindAllProductRequest) returns (ApiResponsePaginationProductDeleteAt) {}
    rpc FindByTrashed(FindAllProductRequest) returns (ApiResponsePaginationProductDeleteAt) {}

}
