syntax = "proto3";

package pb.product;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "product/product_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/products;products";

service ProductCommandService {
    rpc Create(CreateProductRequest) returns (ApiResponseProduct);
    rpc Update(UpdateProductRequest) returns (ApiResponseProduct);
    rpc TrashedProduct(FindByIdProductRequest) returns (ApiResponseProductDeleteAt);
    rpc RestoreProduct(FindByIdProductRequest) returns (ApiResponseProductDeleteAt);
    rpc DeleteProductPermanent(FindByIdProductRequest) returns (ApiResponseProductDelete);
    rpc RestoreAllProduct(google.protobuf.Empty) returns (ApiResponseProductAll){}
    rpc DeleteAllProductPermanent(google.protobuf.Empty) returns (ApiResponseProductAll){}
    rpc DecrementStock(AdjustProductStockRequest) returns (ApiResponseProduct);
    rpc IncrementStock(AdjustProductStockRequest) returns (ApiResponseProduct);
}
