// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: cashier/stats/cashier_stats_byid.proto

package cashiers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CashierStatsByIdService_FindMonthlyTotalSalesById_FullMethodName = "/pb.cashier.stats.CashierStatsByIdService/FindMonthlyTotalSalesById"
	CashierStatsByIdService_FindYearlyTotalSalesById_FullMethodName  = "/pb.cashier.stats.CashierStatsByIdService/FindYearlyTotalSalesById"
	CashierStatsByIdService_FindMonthSalesById_FullMethodName        = "/pb.cashier.stats.CashierStatsByIdService/FindMonthSalesById"
	CashierStatsByIdService_FindYearSalesById_FullMethodName         = "/pb.cashier.stats.CashierStatsByIdService/FindYearSalesById"
)

// CashierStatsByIdServiceClient is the client API for CashierStatsByIdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CashierStatsByIdServiceClient interface {
	FindMonthlyTotalSalesById(ctx context.Context, in *FindYearMonthTotalSalesById, opts ...grpc.CallOption) (*ApiResponseCashierMonthlyTotalSales, error)
	FindYearlyTotalSalesById(ctx context.Context, in *FindYearTotalSalesById, opts ...grpc.CallOption) (*ApiResponseCashierYearlyTotalSales, error)
	FindMonthSalesById(ctx context.Context, in *FindYearCashierById, opts ...grpc.CallOption) (*ApiResponseCashierMonthSales, error)
	FindYearSalesById(ctx context.Context, in *FindYearCashierById, opts ...grpc.CallOption) (*ApiResponseCashierYearSales, error)
}

type cashierStatsByIdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCashierStatsByIdServiceClient(cc grpc.ClientConnInterface) CashierStatsByIdServiceClient {
	return &cashierStatsByIdServiceClient{cc}
}

func (c *cashierStatsByIdServiceClient) FindMonthlyTotalSalesById(ctx context.Context, in *FindYearMonthTotalSalesById, opts ...grpc.CallOption) (*ApiResponseCashierMonthlyTotalSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCashierMonthlyTotalSales)
	err := c.cc.Invoke(ctx, CashierStatsByIdService_FindMonthlyTotalSalesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsByIdServiceClient) FindYearlyTotalSalesById(ctx context.Context, in *FindYearTotalSalesById, opts ...grpc.CallOption) (*ApiResponseCashierYearlyTotalSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCashierYearlyTotalSales)
	err := c.cc.Invoke(ctx, CashierStatsByIdService_FindYearlyTotalSalesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsByIdServiceClient) FindMonthSalesById(ctx context.Context, in *FindYearCashierById, opts ...grpc.CallOption) (*ApiResponseCashierMonthSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCashierMonthSales)
	err := c.cc.Invoke(ctx, CashierStatsByIdService_FindMonthSalesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierStatsByIdServiceClient) FindYearSalesById(ctx context.Context, in *FindYearCashierById, opts ...grpc.CallOption) (*ApiResponseCashierYearSales, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCashierYearSales)
	err := c.cc.Invoke(ctx, CashierStatsByIdService_FindYearSalesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CashierStatsByIdServiceServer is the server API for CashierStatsByIdService service.
// All implementations must embed UnimplementedCashierStatsByIdServiceServer
// for forward compatibility.
type CashierStatsByIdServiceServer interface {
	FindMonthlyTotalSalesById(context.Context, *FindYearMonthTotalSalesById) (*ApiResponseCashierMonthlyTotalSales, error)
	FindYearlyTotalSalesById(context.Context, *FindYearTotalSalesById) (*ApiResponseCashierYearlyTotalSales, error)
	FindMonthSalesById(context.Context, *FindYearCashierById) (*ApiResponseCashierMonthSales, error)
	FindYearSalesById(context.Context, *FindYearCashierById) (*ApiResponseCashierYearSales, error)
	mustEmbedUnimplementedCashierStatsByIdServiceServer()
}

// UnimplementedCashierStatsByIdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCashierStatsByIdServiceServer struct{}

func (UnimplementedCashierStatsByIdServiceServer) FindMonthlyTotalSalesById(context.Context, *FindYearMonthTotalSalesById) (*ApiResponseCashierMonthlyTotalSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalSalesById not implemented")
}
func (UnimplementedCashierStatsByIdServiceServer) FindYearlyTotalSalesById(context.Context, *FindYearTotalSalesById) (*ApiResponseCashierYearlyTotalSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalSalesById not implemented")
}
func (UnimplementedCashierStatsByIdServiceServer) FindMonthSalesById(context.Context, *FindYearCashierById) (*ApiResponseCashierMonthSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthSalesById not implemented")
}
func (UnimplementedCashierStatsByIdServiceServer) FindYearSalesById(context.Context, *FindYearCashierById) (*ApiResponseCashierYearSales, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearSalesById not implemented")
}
func (UnimplementedCashierStatsByIdServiceServer) mustEmbedUnimplementedCashierStatsByIdServiceServer() {
}
func (UnimplementedCashierStatsByIdServiceServer) testEmbeddedByValue() {}

// UnsafeCashierStatsByIdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CashierStatsByIdServiceServer will
// result in compilation errors.
type UnsafeCashierStatsByIdServiceServer interface {
	mustEmbedUnimplementedCashierStatsByIdServiceServer()
}

func RegisterCashierStatsByIdServiceServer(s grpc.ServiceRegistrar, srv CashierStatsByIdServiceServer) {
	// If the following call panics, it indicates UnimplementedCashierStatsByIdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CashierStatsByIdService_ServiceDesc, srv)
}

func _CashierStatsByIdService_FindMonthlyTotalSalesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalSalesById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByIdServiceServer).FindMonthlyTotalSalesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByIdService_FindMonthlyTotalSalesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByIdServiceServer).FindMonthlyTotalSalesById(ctx, req.(*FindYearMonthTotalSalesById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsByIdService_FindYearlyTotalSalesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalSalesById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByIdServiceServer).FindYearlyTotalSalesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByIdService_FindYearlyTotalSalesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByIdServiceServer).FindYearlyTotalSalesById(ctx, req.(*FindYearTotalSalesById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsByIdService_FindMonthSalesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCashierById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByIdServiceServer).FindMonthSalesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByIdService_FindMonthSalesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByIdServiceServer).FindMonthSalesById(ctx, req.(*FindYearCashierById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierStatsByIdService_FindYearSalesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCashierById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsByIdServiceServer).FindYearSalesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsByIdService_FindYearSalesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsByIdServiceServer).FindYearSalesById(ctx, req.(*FindYearCashierById))
	}
	return interceptor(ctx, in, info, handler)
}

// CashierStatsByIdService_ServiceDesc is the grpc.ServiceDesc for CashierStatsByIdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CashierStatsByIdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.cashier.stats.CashierStatsByIdService",
	HandlerType: (*CashierStatsByIdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalSalesById",
			Handler:    _CashierStatsByIdService_FindMonthlyTotalSalesById_Handler,
		},
		{
			MethodName: "FindYearlyTotalSalesById",
			Handler:    _CashierStatsByIdService_FindYearlyTotalSalesById_Handler,
		},
		{
			MethodName: "FindMonthSalesById",
			Handler:    _CashierStatsByIdService_FindMonthSalesById_Handler,
		},
		{
			MethodName: "FindYearSalesById",
			Handler:    _CashierStatsByIdService_FindYearSalesById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cashier/stats/cashier_stats_byid.proto",
}
