// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cashier/stats/cashier_stats.proto

package cashiers

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_cashier_stats_cashier_stats_proto protoreflect.FileDescriptor

const file_cashier_stats_cashier_stats_proto_rawDesc = "" +
	"\n" +
	"!cashier/stats/cashier_stats.proto\x12\x10pb.cashier.stats\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1ccashier/cashier_common.proto2\xa4\x03\n" +
	"\x13CashierStatsService\x12o\n" +
	"\x15FindMonthlyTotalSales\x12#.pb.cashier.FindYearMonthTotalSales\x1a/.pb.cashier.ApiResponseCashierMonthlyTotalSales\"\x00\x12h\n" +
	"\x14FindYearlyTotalSales\x12\x1e.pb.cashier.FindYearTotalSales\x1a..pb.cashier.ApiResponseCashierYearlyTotalSales\"\x00\x12Y\n" +
	"\x0eFindMonthSales\x12\x1b.pb.cashier.FindYearCashier\x1a(.pb.cashier.ApiResponseCashierMonthSales\"\x00\x12W\n" +
	"\rFindYearSales\x12\x1b.pb.cashier.FindYearCashier\x1a'.pb.cashier.ApiResponseCashierYearSales\"\x00BCZAgithub.com/MamangRust/monolith-point-of-sale-pb/cashiers;cashiersb\x06proto3"

var file_cashier_stats_cashier_stats_proto_goTypes = []any{
	(*FindYearMonthTotalSales)(nil),             // 0: pb.cashier.FindYearMonthTotalSales
	(*FindYearTotalSales)(nil),                  // 1: pb.cashier.FindYearTotalSales
	(*FindYearCashier)(nil),                     // 2: pb.cashier.FindYearCashier
	(*ApiResponseCashierMonthlyTotalSales)(nil), // 3: pb.cashier.ApiResponseCashierMonthlyTotalSales
	(*ApiResponseCashierYearlyTotalSales)(nil),  // 4: pb.cashier.ApiResponseCashierYearlyTotalSales
	(*ApiResponseCashierMonthSales)(nil),        // 5: pb.cashier.ApiResponseCashierMonthSales
	(*ApiResponseCashierYearSales)(nil),         // 6: pb.cashier.ApiResponseCashierYearSales
}
var file_cashier_stats_cashier_stats_proto_depIdxs = []int32{
	0, // 0: pb.cashier.stats.CashierStatsService.FindMonthlyTotalSales:input_type -> pb.cashier.FindYearMonthTotalSales
	1, // 1: pb.cashier.stats.CashierStatsService.FindYearlyTotalSales:input_type -> pb.cashier.FindYearTotalSales
	2, // 2: pb.cashier.stats.CashierStatsService.FindMonthSales:input_type -> pb.cashier.FindYearCashier
	2, // 3: pb.cashier.stats.CashierStatsService.FindYearSales:input_type -> pb.cashier.FindYearCashier
	3, // 4: pb.cashier.stats.CashierStatsService.FindMonthlyTotalSales:output_type -> pb.cashier.ApiResponseCashierMonthlyTotalSales
	4, // 5: pb.cashier.stats.CashierStatsService.FindYearlyTotalSales:output_type -> pb.cashier.ApiResponseCashierYearlyTotalSales
	5, // 6: pb.cashier.stats.CashierStatsService.FindMonthSales:output_type -> pb.cashier.ApiResponseCashierMonthSales
	6, // 7: pb.cashier.stats.CashierStatsService.FindYearSales:output_type -> pb.cashier.ApiResponseCashierYearSales
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cashier_stats_cashier_stats_proto_init() }
func file_cashier_stats_cashier_stats_proto_init() {
	if File_cashier_stats_cashier_stats_proto != nil {
		return
	}
	file_cashier_cashier_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cashier_stats_cashier_stats_proto_rawDesc), len(file_cashier_stats_cashier_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cashier_stats_cashier_stats_proto_goTypes,
		DependencyIndexes: file_cashier_stats_cashier_stats_proto_depIdxs,
	}.Build()
	File_cashier_stats_cashier_stats_proto = out.File
	file_cashier_stats_cashier_stats_proto_goTypes = nil
	file_cashier_stats_cashier_stats_proto_depIdxs = nil
}
