apiVersion: v1
kind: Service
metadata:
  name: cashier
  namespace: point-of-sale
spec:
  selector:
    app: cashier
  ports:
    - name: grpc
      port: 50061
      targetPort: 50061
  type: ClusterIP
