syntax = "proto3";

package pb.cashier.stats;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "cashier/cashier_common.proto";

option go_package = "github.com/MamangRust/monolith-point-of-sale-pb/cashiers;cashiers";

service CashierStatsByIdService {
    rpc FindMonthlyTotalSalesById(FindYearMonthTotalSalesById) returns (ApiResponseCashierMonthlyTotalSales){}
    rpc FindYearlyTotalSalesById(FindYearTotalSalesById) returns (ApiResponseCashierYearlyTotalSales){}
    rpc FindMonthSalesById(FindYearCashierById) returns(ApiResponseCashierMonthSales){}
    rpc FindYearSalesById(FindYearCashierById) returns(ApiResponseCashierYearSales){}
}
