// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transaction/transaction_command.proto

package transactions

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_transaction_transaction_command_proto protoreflect.FileDescriptor

const file_transaction_transaction_command_proto_rawDesc = "" +
	"\n" +
	"%transaction/transaction_command.proto\x12\x0epb.transaction\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a$transaction/transaction_common.proto2\xf3\x05\n" +
	"\x19TransactionCommandService\x12Z\n" +
	"\x06Create\x12(.pb.transaction.CreateTransactionRequest\x1a&.pb.transaction.ApiResponseTransaction\x12Z\n" +
	"\x06Update\x12(.pb.transaction.UpdateTransactionRequest\x1a&.pb.transaction.ApiResponseTransaction\x12p\n" +
	"\x12TrashedTransaction\x12*.pb.transaction.FindByIdTransactionRequest\x1a..pb.transaction.ApiResponseTransactionDeleteAt\x12p\n" +
	"\x12RestoreTransaction\x12*.pb.transaction.FindByIdTransactionRequest\x1a..pb.transaction.ApiResponseTransactionDeleteAt\x12v\n" +
	"\x1aDeleteTransactionPermanent\x12*.pb.transaction.FindByIdTransactionRequest\x1a,.pb.transaction.ApiResponseTransactionDelete\x12\\\n" +
	"\x15RestoreAllTransaction\x12\x16.google.protobuf.Empty\x1a).pb.transaction.ApiResponseTransactionAll\"\x00\x12d\n" +
	"\x1dDeleteAllTransactionPermanent\x12\x16.google.protobuf.Empty\x1a).pb.transaction.ApiResponseTransactionAll\"\x00BKZIgithub.com/MamangRust/monolith-point-of-sale-pb/transactions;transactionsb\x06proto3"

var file_transaction_transaction_command_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),       // 0: pb.transaction.CreateTransactionRequest
	(*UpdateTransactionRequest)(nil),       // 1: pb.transaction.UpdateTransactionRequest
	(*FindByIdTransactionRequest)(nil),     // 2: pb.transaction.FindByIdTransactionRequest
	(*emptypb.Empty)(nil),                  // 3: google.protobuf.Empty
	(*ApiResponseTransaction)(nil),         // 4: pb.transaction.ApiResponseTransaction
	(*ApiResponseTransactionDeleteAt)(nil), // 5: pb.transaction.ApiResponseTransactionDeleteAt
	(*ApiResponseTransactionDelete)(nil),   // 6: pb.transaction.ApiResponseTransactionDelete
	(*ApiResponseTransactionAll)(nil),      // 7: pb.transaction.ApiResponseTransactionAll
}
var file_transaction_transaction_command_proto_depIdxs = []int32{
	0, // 0: pb.transaction.TransactionCommandService.Create:input_type -> pb.transaction.CreateTransactionRequest
	1, // 1: pb.transaction.TransactionCommandService.Update:input_type -> pb.transaction.UpdateTransactionRequest
	2, // 2: pb.transaction.TransactionCommandService.TrashedTransaction:input_type -> pb.transaction.FindByIdTransactionRequest
	2, // 3: pb.transaction.TransactionCommandService.RestoreTransaction:input_type -> pb.transaction.FindByIdTransactionRequest
	2, // 4: pb.transaction.TransactionCommandService.DeleteTransactionPermanent:input_type -> pb.transaction.FindByIdTransactionRequest
	3, // 5: pb.transaction.TransactionCommandService.RestoreAllTransaction:input_type -> google.protobuf.Empty
	3, // 6: pb.transaction.TransactionCommandService.DeleteAllTransactionPermanent:input_type -> google.protobuf.Empty
	4, // 7: pb.transaction.TransactionCommandService.Create:output_type -> pb.transaction.ApiResponseTransaction
	4, // 8: pb.transaction.TransactionCommandService.Update:output_type -> pb.transaction.ApiResponseTransaction
	5, // 9: pb.transaction.TransactionCommandService.TrashedTransaction:output_type -> pb.transaction.ApiResponseTransactionDeleteAt
	5, // 10: pb.transaction.TransactionCommandService.RestoreTransaction:output_type -> pb.transaction.ApiResponseTransactionDeleteAt
	6, // 11: pb.transaction.TransactionCommandService.DeleteTransactionPermanent:output_type -> pb.transaction.ApiResponseTransactionDelete
	7, // 12: pb.transaction.TransactionCommandService.RestoreAllTransaction:output_type -> pb.transaction.ApiResponseTransactionAll
	7, // 13: pb.transaction.TransactionCommandService.DeleteAllTransactionPermanent:output_type -> pb.transaction.ApiResponseTransactionAll
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_transaction_command_proto_init() }
func file_transaction_transaction_command_proto_init() {
	if File_transaction_transaction_command_proto != nil {
		return
	}
	file_transaction_transaction_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_transaction_command_proto_rawDesc), len(file_transaction_transaction_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_transaction_command_proto_goTypes,
		DependencyIndexes: file_transaction_transaction_command_proto_depIdxs,
	}.Build()
	File_transaction_transaction_command_proto = out.File
	file_transaction_transaction_command_proto_goTypes = nil
	file_transaction_transaction_command_proto_depIdxs = nil
}
