// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transaction/stats/transaction_stats.proto

package transactions

import (
	_ "github.com/MamangRust/monolith-point-of-sale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_transaction_stats_transaction_stats_proto protoreflect.FileDescriptor

const file_transaction_stats_transaction_stats_proto_rawDesc = "" +
	"\n" +
	")transaction/stats/transaction_stats.proto\x12\x14pb.transaction.stats\x1a\x10common/api.proto\x1a$transaction/transaction_common.proto2\x80\b\n" +
	"\x17TransactionStatsService\x12\x80\x01\n" +
	"\x16FindMonthStatusSuccess\x12,.pb.transaction.FindMonthlyTransactionStatus\x1a8.pb.transaction.ApiResponseTransactionMonthAmountSuccess\x12}\n" +
	"\x15FindYearStatusSuccess\x12+.pb.transaction.FindYearlyTransactionStatus\x1a7.pb.transaction.ApiResponseTransactionYearAmountSuccess\x12~\n" +
	"\x15FindMonthStatusFailed\x12,.pb.transaction.FindMonthlyTransactionStatus\x1a7.pb.transaction.ApiResponseTransactionMonthAmountFailed\x12{\n" +
	"\x14FindYearStatusFailed\x12+.pb.transaction.FindYearlyTransactionStatus\x1a6.pb.transaction.ApiResponseTransactionYearAmountFailed\x12z\n" +
	"\x16FindMonthMethodSuccess\x12&.pb.transaction.MonthTransactionMethod\x1a8.pb.transaction.ApiResponseTransactionMonthPaymentMethod\x12w\n" +
	"\x15FindYearMethodSuccess\x12%.pb.transaction.YearTransactionMethod\x1a7.pb.transaction.ApiResponseTransactionYearPaymentmethod\x12y\n" +
	"\x15FindMonthMethodFailed\x12&.pb.transaction.MonthTransactionMethod\x1a8.pb.transaction.ApiResponseTransactionMonthPaymentMethod\x12v\n" +
	"\x14FindYearMethodFailed\x12%.pb.transaction.YearTransactionMethod\x1a7.pb.transaction.ApiResponseTransactionYearPaymentmethodBKZIgithub.com/MamangRust/monolith-point-of-sale-pb/transactions;transactionsb\x06proto3"

var file_transaction_stats_transaction_stats_proto_goTypes = []any{
	(*FindMonthlyTransactionStatus)(nil),             // 0: pb.transaction.FindMonthlyTransactionStatus
	(*FindYearlyTransactionStatus)(nil),              // 1: pb.transaction.FindYearlyTransactionStatus
	(*MonthTransactionMethod)(nil),                   // 2: pb.transaction.MonthTransactionMethod
	(*YearTransactionMethod)(nil),                    // 3: pb.transaction.YearTransactionMethod
	(*ApiResponseTransactionMonthAmountSuccess)(nil), // 4: pb.transaction.ApiResponseTransactionMonthAmountSuccess
	(*ApiResponseTransactionYearAmountSuccess)(nil),  // 5: pb.transaction.ApiResponseTransactionYearAmountSuccess
	(*ApiResponseTransactionMonthAmountFailed)(nil),  // 6: pb.transaction.ApiResponseTransactionMonthAmountFailed
	(*ApiResponseTransactionYearAmountFailed)(nil),   // 7: pb.transaction.ApiResponseTransactionYearAmountFailed
	(*ApiResponseTransactionMonthPaymentMethod)(nil), // 8: pb.transaction.ApiResponseTransactionMonthPaymentMethod
	(*ApiResponseTransactionYearPaymentmethod)(nil),  // 9: pb.transaction.ApiResponseTransactionYearPaymentmethod
}
var file_transaction_stats_transaction_stats_proto_depIdxs = []int32{
	0, // 0: pb.transaction.stats.TransactionStatsService.FindMonthStatusSuccess:input_type -> pb.transaction.FindMonthlyTransactionStatus
	1, // 1: pb.transaction.stats.TransactionStatsService.FindYearStatusSuccess:input_type -> pb.transaction.FindYearlyTransactionStatus
	0, // 2: pb.transaction.stats.TransactionStatsService.FindMonthStatusFailed:input_type -> pb.transaction.FindMonthlyTransactionStatus
	1, // 3: pb.transaction.stats.TransactionStatsService.FindYearStatusFailed:input_type -> pb.transaction.FindYearlyTransactionStatus
	2, // 4: pb.transaction.stats.TransactionStatsService.FindMonthMethodSuccess:input_type -> pb.transaction.MonthTransactionMethod
	3, // 5: pb.transaction.stats.TransactionStatsService.FindYearMethodSuccess:input_type -> pb.transaction.YearTransactionMethod
	2, // 6: pb.transaction.stats.TransactionStatsService.FindMonthMethodFailed:input_type -> pb.transaction.MonthTransactionMethod
	3, // 7: pb.transaction.stats.TransactionStatsService.FindYearMethodFailed:input_type -> pb.transaction.YearTransactionMethod
	4, // 8: pb.transaction.stats.TransactionStatsService.FindMonthStatusSuccess:output_type -> pb.transaction.ApiResponseTransactionMonthAmountSuccess
	5, // 9: pb.transaction.stats.TransactionStatsService.FindYearStatusSuccess:output_type -> pb.transaction.ApiResponseTransactionYearAmountSuccess
	6, // 10: pb.transaction.stats.TransactionStatsService.FindMonthStatusFailed:output_type -> pb.transaction.ApiResponseTransactionMonthAmountFailed
	7, // 11: pb.transaction.stats.TransactionStatsService.FindYearStatusFailed:output_type -> pb.transaction.ApiResponseTransactionYearAmountFailed
	8, // 12: pb.transaction.stats.TransactionStatsService.FindMonthMethodSuccess:output_type -> pb.transaction.ApiResponseTransactionMonthPaymentMethod
	9, // 13: pb.transaction.stats.TransactionStatsService.FindYearMethodSuccess:output_type -> pb.transaction.ApiResponseTransactionYearPaymentmethod
	8, // 14: pb.transaction.stats.TransactionStatsService.FindMonthMethodFailed:output_type -> pb.transaction.ApiResponseTransactionMonthPaymentMethod
	9, // 15: pb.transaction.stats.TransactionStatsService.FindYearMethodFailed:output_type -> pb.transaction.ApiResponseTransactionYearPaymentmethod
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_stats_transaction_stats_proto_init() }
func file_transaction_stats_transaction_stats_proto_init() {
	if File_transaction_stats_transaction_stats_proto != nil {
		return
	}
	file_transaction_transaction_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_stats_transaction_stats_proto_rawDesc), len(file_transaction_stats_transaction_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_stats_transaction_stats_proto_goTypes,
		DependencyIndexes: file_transaction_stats_transaction_stats_proto_depIdxs,
	}.Build()
	File_transaction_stats_transaction_stats_proto = out.File
	file_transaction_stats_transaction_stats_proto_goTypes = nil
	file_transaction_stats_transaction_stats_proto_depIdxs = nil
}
