apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pos-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pos
  source:
    repoURL: https://github.com/MamangRust/modular-monolith-vertx-point-of-sale.git
    targetRevision: main
    path: deployments/kubernetes/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: point-of-sale
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
