apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pos
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Point-of-Sale modular monolith project
  sourceRepos:
  - '*'
  destinations:
  - namespace: point-of-sale
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
